const words = [
    {"en": "World", "pr": "уорлд", "ky": "Дүйнө", "ex": "The world is beautiful.", "ex_pr": "Зэ уорлд из бьютифул.", "ex_ky": "Дүйнө кооз."},
    {"en": "Travel", "pr": "трэвэл", "ky": "Саякаттоо", "ex": "I want to travel.", "ex_pr": "Ай уонт ту трэвэл.", "ex_ky": "Мен саякаттагым келет."},
    {"en": "Book", "pr": "бук", "ky": "Китеп", "ex": "I read a good book.", "ex_pr": "Ай рид э гуд бук.", "ex_ky": "Мен жакшы китеп окудум."},
    {"en": "Time", "pr": "тайм", "ky": "Убакыт", "ex": "Time is money.", "ex_pr": "Тайм из мани.", "ex_ky": "Убакыт – бул акча."},
    {"en": "Friend", "pr": "фрэнд", "ky": "Дос", "ex": "He is my friend.", "ex_pr": "Хи из май фрэнд.", "ex_ky": "Ал менин досум."},
    {"en": "Home", "pr": "хоум", "ky": "Үй", "ex": "I love my home.", "ex_pr": "Ай лав май хоум.", "ex_ky": "Мен үйүмдү жакшы көрөм."},
    {"en": "Love", "pr": "лав", "ky": "Сүйүү", "ex": "Love is all around.", "ex_pr": "Лав из ол эраунд.", "ex_ky": "Сүйүү бар жерде."},
    {"en": "Peace", "pr": "пиис", "ky": "Тынчтык", "ex": "We need peace.", "ex_pr": "Уи ниид пиис.", "ex_ky": "Бизге тынчтык керек."},
    {"en": "Joy", "pr": "джой", "ky": "Кубаныч", "ex": "Joy fills my heart.", "ex_pr": "Джой филз май харт.", "ex_ky": "Кубаныч жүрөгүмдү толтурат."},
    {"en": "Light", "pr": "лайт", "ky": "Жарык", "ex": "Turn on the light.", "ex_pr": "Тёрн он зэ лайт.", "ex_ky": "Жарыкты күйгүз."},
    {"en": "Sun", "pr": "сан", "ky": "Күн", "ex": "The sun shines bright.", "ex_pr": "Зэ сан шайнз брайт.", "ex_ky": "Күн жаркырайт."},
    {"en": "Moon", "pr": "муун", "ky": "Ай", "ex": "Moonlight is soft.", "ex_pr": "Муунлайт из софт.", "ex_ky": "Ай нуру жумшак."},
    {"en": "Star", "pr": "стар", "ky": "Жылдыз", "ex": "Look at the star.", "ex_pr": "Лук эт зэ стар.", "ex_ky": "Жылдызга кара."},
    {"en": "Water", "pr": "уотер", "ky": "Суу", "ex": "Water is life.", "ex_pr": "Уотер из лайф.", "ex_ky": "Суу – жашоо."},
    {"en": "Fire", "pr": "файер", "ky": "От", "ex": "Fire is hot.", "ex_pr": "Файер из хот.", "ex_ky": "От ысык."},
    {"en": "Tree", "pr": "трии", "ky": "Дарак", "ex": "The tree is tall.", "ex_pr": "Зэ трии из тоол.", "ex_ky": "Дарак бийик."},
    {"en": "Flower", "pr": "флауэр", "ky": "Гүл", "ex": "The flower blooms.", "ex_pr": "Зэ флауэр блумз.", "ex_ky": "Гүл ачылат."},
    {"en": "Bird", "pr": "бёрд", "ky": "Куш", "ex": "The bird flies high.", "ex_pr": "Зэ бёрд флайз хай.", "ex_ky": "Куш бийик учат."},
    {"en": "Fish", "pr": "фиш", "ky": "Балык", "ex": "I like fish.", "ex_pr": "Ай лайк фиш.", "ex_ky": "Мага балык жагат."},
    {"en": "Cat", "pr": "кэт", "ky": "Мышык", "ex": "The cat sleeps.", "ex_pr": "Зэ кэт слипс.", "ex_ky": "Мышык уктайт."},
    {"en": "Dog", "pr": "дог", "ky": "Ит", "ex": "The dog barks.", "ex_pr": "Зэ дог баркс.", "ex_ky": "Ит үрөт."},
    {"en": "Horse", "pr": "хорс", "ky": "Жылкы", "ex": "The horse runs fast.", "ex_pr": "Зэ хорс ранс фаст.", "ex_ky": "Жылкы тез чуркайт."},
    {"en": "Cow", "pr": "кау", "ky": "Уй", "ex": "The cow gives milk.", "ex_pr": "Зэ кау гивз милк.", "ex_ky": "Уй сүт берет."},
    {"en": "Sheep", "pr": "шиип", "ky": "Кой", "ex": "Sheep eat grass.", "ex_pr": "Шиип ит граас.", "ex_ky": "Кой чөп жейт."},
    {"en": "Goat", "pr": "гоут", "ky": "Эчки", "ex": "The goat climbs.", "ex_pr": "Зэ гоут клаймз.", "ex_ky": "Эчки чыгат."},
    {"en": "Food", "pr": "фууд", "ky": "Тамак", "ex": "The food is delicious.", "ex_pr": "Зэ фууд из дилишес.", "ex_ky": "Тамак даамдуу."},
    {"en": "Bread", "pr": "брэд", "ky": "Нан", "ex": "Fresh bread is good.", "ex_pr": "Фрэш брэд из гуд.", "ex_ky": "Жаңы нан жакшы."},
    {"en": "Milk", "pr": "милк", "ky": "Сүт", "ex": "Milk is healthy.", "ex_pr": "Милк из хэлси.", "ex_ky": "Сүт пайдалуу."},
    {"en": "Tea", "pr": "тии", "ky": "Чай", "ex": "I drink tea.", "ex_pr": "Ай дринк тии.", "ex_ky": "Мен чай ичем."},
    {"en": "Coffee", "pr": "кофи", "ky": "Кофе", "ex": "Coffee wakes me up.", "ex_pr": "Кофи вэйкс ми ап.", "ex_ky": "Кофе мени ойготот."},
    {"en": "Fruit", "pr": "фруут", "ky": "Жемиш", "ex": "Fruit is sweet.", "ex_pr": "Фруут из суиит.", "ex_ky": "Жемиш таттуу."},
    {"en": "Apple", "pr": "эпл", "ky": "Алма", "ex": "An apple a day.", "ex_pr": "Эн эпл э дэй.", "ex_ky": "Күнүнө бир алма."},
    {"en": "Orange", "pr": "оринж", "ky": "Апельсин", "ex": "Orange is orange.", "ex_pr": "Оринж из оринж.", "ex_ky": "Апельсин кызгылт сары."},
    {"en": "Banana", "pr": "бэнэнэ", "ky": "Банан", "ex": "I eat a banana.", "ex_pr": "Ай ит э бэнэнэ.", "ex_ky": "Мен банан жейм."},
    {"en": "Meat", "pr": "миит", "ky": "Эт", "ex": "Meat has protein.", "ex_pr": "Миит хэз проутин.", "ex_ky": "Этте белок бар."},
    {"en": "Work", "pr": "уорк", "ky": "Жумуш", "ex": "I go to work.", "ex_pr": "Ай гоу ту уорк.", "ex_ky": "Мен жумушка барам."},
    {"en": "Study", "pr": "стади", "ky": "Окуу", "ex": "I study every day.", "ex_pr": "Ай стади эври дэй.", "ex_ky": "Мен күн сайын окуйм."},
    {"en": "Learn", "pr": "лёрн", "ky": "Үйрөнүү", "ex": "Learn new words.", "ex_pr": "Лёрн нью уордз.", "ex_ky": "Жаңы сөздөрдү үйрөн."},
    {"en": "Teach", "pr": "тиич", "ky": "Окутуу", "ex": "She teaches well.", "ex_pr": "Ши тиичез уэл.", "ex_ky": "Ал жакшы окутат."},
    {"en": "School", "pr": "скуул", "ky": "Мектеп", "ex": "School is important.", "ex_pr": "Скуул из импортэнт.", "ex_ky": "Мектеп маанилүү."},
    {"en": "University", "pr": "юнивёрсити", "ky": "Университет", "ex": "He studies at university.", "ex_pr": "Хи стадиз эт юнивёрсити.", "ex_ky": "Ал университетте окуйт."},
    {"en": "Teacher", "pr": "тиичер", "ky": "Мугалим", "ex": "The teacher helps.", "ex_pr": "Зэ тиичер хелпс.", "ex_ky": "Мугалим жардам берет."},
    {"en": "Student", "pr": "стюдэнт", "ky": "Окуучу", "ex": "The student listens.", "ex_pr": "Зэ стюдэнт листэнс.", "ex_ky": "Окуучу угат."},
    {"en": "Lesson", "pr": "лесон", "ky": "Сабак", "ex": "The lesson starts.", "ex_pr": "Зэ лес он стартс.", "ex_ky": "Сабак башталат."},
    {"en": "Language", "pr": "лэнгвидж", "ky": "Тил", "ex": "English is a language.", "ex_pr": "Инглиш из э лэнгвидж.", "ex_ky": "Англисче – тил."},
    {"en": "Word", "pr": "уорд", "ky": "Сөз", "ex": "This is a new word.", "ex_pr": "Зис из э нью уорд.", "ex_ky": "Бул жаңы сөз."},
    {"en": "Sentence", "pr": "сентэнс", "ky": "Сүйлөм", "ex": "Make a sentence.", "ex_pr": "Мэйк э сентэнс.", "ex_ky": "Сүйлөм түз."},
    {"en": "Meaning", "pr": "миининг", "ky": "Маани", "ex": "What is the meaning?", "ex_pr": "Уот из зэ миининг?", "ex_ky": "Мааниси эмне?"},
    {"en": "Dictionary", "pr": "дикшонэри", "ky": "Сөздүк", "ex": "Use the dictionary.", "ex_pr": "Юз зэ дикшонэри.", "ex_ky": "Сөздүктү колдон."},
    {"en": "Grammar", "pr": "грэмэр", "ky": "Грамматика", "ex": "Grammar rules.", "ex_pr": "Грэмэр рулз.", "ex_ky": "Грамматика эрежелери."},
    {"en": "Read", "pr": "риид", "ky": "Окуу", "ex": "I read books.", "ex_pr": "Ай риид букс.", "ex_ky": "Мен китеп окуйм."},
    {"en": "Write", "pr": "райт", "ky": "Жазуу", "ex": "I write a letter.", "ex_pr": "Ай райт э летэр.", "ex_ky": "Мен кат жазам."},
    {"en": "Speak", "pr": "спиик", "ky": "Сүйлөө", "ex": "Speak slowly.", "ex_pr": "Спиик слоули.", "ex_ky": "Жай сүйлө."},
    {"en": "Listen", "pr": "лисэн", "ky": "Угуу", "ex": "Listen carefully.", "ex_pr": "Лисэн кээфуллли.", "ex_ky": "Кунт коюп угу."},
    {"en": "Watch", "pr": "уоч", "ky": "Көрүү", "ex": "Watch the movie.", "ex_pr": "Уоч зэ муви.", "ex_ky": "Тасманы көр."},
    {"en": "See", "pr": "сии", "ky": "Көрүү", "ex": "I see you.", "ex_pr": "Ай сии ю.", "ex_ky": "Мен сени көрөм."},
    {"en": "Look", "pr": "лук", "ky": "Кара", "ex": "Look at me.", "ex_pr": "Лук эт ми.", "ex_ky": "Мага кара."},
    {"en": "Happy", "pr": "хэпи", "ky": "Бактылуу", "ex": "I am happy.", "ex_pr": "Ай эм хэпи.", "ex_ky": "Мен бактылуумун."},
    {"en": "Sad", "pr": "сэд", "ky": "Капа", "ex": "He feels sad.", "ex_pr": "Хи фиилз сэд.", "ex_ky": "Ал капа болот."},
    {"en": "Big", "pr": "биг", "ky": "Чоң", "ex": "A big house.", "ex_pr": "Э биг хаус.", "ex_ky": "Чоң үй."},
    {"en": "Small", "pr": "смоол", "ky": "Кичине", "ex": "A small car.", "ex_pr": "Э смоол каар.", "ex_ky": "Кичине унаа."},
    {"en": "Fast", "pr": "фааст", "ky": "Тез", "ex": "He runs fast.", "ex_pr": "Хи ранс фааст.", "ex_ky": "Ал тез чуркайт."},
    {"en": "Slow", "pr": "слоу", "ky": "Жай", "ex": "Walk slow.", "ex_pr": "Уок слоу.", "ex_ky": "Жай бас."},
    {"en": "New", "pr": "нью", "ky": "Жаңы", "ex": "A new phone.", "ex_pr": "Э нью фоун.", "ex_ky": "Жаңы телефон."},
    {"en": "Old", "pr": "оулд", "ky": "Эски", "ex": "An old tree.", "ex_pr": "Эн оулд трии.", "ex_ky": "Эски дарак."},
    {"en": "Good", "pr": "гуд", "ky": "Жакшы", "ex": "Good job!", "ex_pr": "Гуд джоб!", "ex_ky": "Жакшы иш!"},
    {"en": "Bad", "pr": "бэд", "ky": "Жаман", "ex": "Bad weather.", "ex_pr": "Бэд уэзер.", "ex_ky": "Жаман аба ырайы."},
    {"en": "Beautiful", "pr": "бьютифул", "ky": "Кооз", "ex": "Beautiful view.", "ex_pr": "Бьютифул вью.", "ex_ky": "Кооз көрүнүш."},
    {"en": "Ugly", "pr": "агли", "ky": "Керсес", "ex": "An ugly face.", "ex_pr": "Эн агли фэйс.", "ex_ky": "Керсес бет."},
    {"en": "Rich", "pr": "рич", "ky": "Бай", "ex": "He is rich.", "ex_pr": "Хи из рич.", "ex_ky": "Ал бай."},
    {"en": "Poor", "pr": "пур", "ky": "Кедей", "ex": "Poor family.", "ex_pr": "Пур фэмили.", "ex_ky": "Кедей үй-бүлө."},
    {"en": "Strong", "pr": "стронг", "ky": "Күчтүү", "ex": "Strong man.", "ex_pr": "Стронг мэн.", "ex_ky": "Күчтүү эркек."},
    {"en": "Weak", "pr": "уиик", "ky": "Алсыз", "ex": "Weak body.", "ex_pr": "Уиик боди.", "ex_ky": "Алсыз дене."},
    {"en": "Young", "pr": "янг", "ky": "Жаш", "ex": "Young people.", "ex_pr": "Янг пиипл.", "ex_ky": "Жаш адамдар."},
    {"en": "Morning", "pr": "морнинг", "ky": "Таң", "ex": "Good morning!", "ex_pr": "Гуд морнинг!", "ex_ky": "Кутмандуу таң!"},
    {"en": "Evening", "pr": "иивнинг", "ky": "Кеч", "ex": "Good evening.", "ex_pr": "Гуд иивнинг.", "ex_ky": "Кечиңиз жакшы өтсүн."},
    {"en": "Night", "pr": "найт", "ky": "Түн", "ex": "Good night.", "ex_pr": "Гуд найт.", "ex_ky": "Түнүңүз бейпил өтсүн."},
    {"en": "Father", "pr": "фаазер", "ky": "Ата", "ex": "My father works.", "ex_pr": "Май фаазер уоркс.", "ex_ky": "Менин атам иштейт."},
    {"en": "Mother", "pr": "мазер", "ky": "Эне", "ex": "My mother cooks.", "ex_pr": "Май мазер кукс.", "ex_ky": "Менин энем тамак жасайт."},
    {"en": "Brother", "pr": "бразер", "ky": "Бир тууган", "ex": "My brother plays.", "ex_pr": "Май бразер плэйз.", "ex_ky": "Менин бир тууганым ойнойт."},
    {"en": "Sister", "pr": "систер", "ky": "Эже/сиңди", "ex": "My sister sings.", "ex_pr": "Май систер сингз.", "ex_ky": "Менин эжем ырдайт."},
    {"en": "Son", "pr": "сан", "ky": "Уул", "ex": "My son studies.", "ex_pr": "Май сан стадиз.", "ex_ky": "Менин уулум окуйт."},
    {"en": "Daughter", "pr": "дотер", "ky": "Кыз", "ex": "My daughter dances.", "ex_pr": "Май дотер дансиз.", "ex_ky": "Менин кызым бийлейт."},
    {"en": "Family", "pr": "фэмили", "ky": "Үй-бүлө", "ex": "Family is important.", "ex_pr": "Фэмили из импортэнт.", "ex_ky": "Үй-бүлө маанилүү."},
    {"en": "People", "pr": "пиипл", "ky": "Адамдар", "ex": "People are kind.", "ex_pr": "Пиипл ар кайнд.", "ex_ky": "Адамдар мээримдүү."},
    {"en": "Child", "pr": "чайлд", "ky": "Бала", "ex": "The child laughs.", "ex_pr": "Зэ чайлд лафс.", "ex_ky": "Бала күлөт."},
    {"en": "Man", "pr": "мэн", "ky": "Эркек", "ex": "The man runs.", "ex_pr": "Зэ мэн ранс.", "ex_ky": "Эркек чуркайт."},
    {"en": "Woman", "pr": "вумэн", "ky": "Аял", "ex": "The woman smiles.", "ex_pr": "Зэ вумэн смайлз.", "ex_ky": "Аял жылмаят."},
    {"en": "Boy", "pr": "бой", "ky": "Бала", "ex": "The boy runs.", "ex_pr": "Зэ бой ранс.", "ex_ky": "Бала чуркайт."},
    {"en": "Girl", "pr": "гёрл", "ky": "Кыз", "ex": "The girl sings.", "ex_pr": "Зэ гёрл сингз.", "ex_ky": "Кыз ырдайт."},
    {"en": "Name", "pr": "нэйм", "ky": "Ат", "ex": "What is your name?", "ex_pr": "Уот из ёр нэйм?", "ex_ky": "Атың ким?"},
    {"en": "City", "pr": "сити", "ky": "Шаар", "ex": "Big city life.", "ex_pr": "Биг сити лайф.", "ex_ky": "Чоң шаар жашоосу."},
    {"en": "Country", "pr": "кантри", "ky": "Өлкө", "ex": "My country is beautiful.", "ex_pr": "Май кантри из бьютифул.", "ex_ky": "Менин өлкөм кооз."},
    {"en": "Mountain", "pr": "маунтин", "ky": "Тоо", "ex": "High mountain.", "ex_pr": "Хай маунтин.", "ex_ky": "Бийик тоо."},
    {"en": "River", "pr": "ривер", "ky": "Дарыя", "ex": "The river flows.", "ex_pr": "Зэ ривер флоуз.", "ex_ky": "Дарыя агат."},
    {"en": "Rain", "pr": "рэйн", "ky": "Жаан", "ex": "Rain falls down.", "ex_pr": "Рэйн фолз даун.", "ex_ky": "Жаан жаайт."},
    {"en": "Snow", "pr": "сноу", "ky": "Кар", "ex": "Snow is white.", "ex_pr": "Сноу из уайт.", "ex_ky": "Кар аппак."},
    {"en": "Summer", "pr": "самер", "ky": "Жай", "ex": "I love summer.", "ex_pr": "Ай лав самер.", "ex_ky": "Мен жайды жакшы көрөм."},
    {"en": "Winter", "pr": "уинтер", "ky": "Кыш", "ex": "Winter is cold.", "ex_pr": "Уинтер из коулд.", "ex_ky": "Кыш суук."},
    {"en": "Spring", "pr": "спринг", "ky": "Жаз", "ex": "Spring brings flowers.", "ex_pr": "Спринг бринтс флауэрс.", "ex_ky": "Жаз гүл алып келет."},
    {"en": "Autumn", "pr": "оутэм", "ky": "Күз", "ex": "Autumn leaves fall.", "ex_pr": "Оутэм лиивз фол.", "ex_ky": "Күздө жалбырактар түшөт."},
    {"en": "Day", "pr": "дэй", "ky": "Күн", "ex": "Have a nice day.", "ex_pr": "Хэв э найс дэй.", "ex_ky": "Күнүңүз жакшы өтсүн."},
    {"en": "Week", "pr": "уиик", "ky": "Апта", "ex": "Seven days a week.", "ex_pr": "Сэвэн дэйз э уиик.", "ex_ky": "Аптада жети күн."},
    {"en": "Month", "pr": "манс", "ky": "Ай", "ex": "This month is busy.", "ex_pr": "Зис манс из бизи.", "ex_ky": "Бул ай бош эмес."},
    {"en": "Year", "pr": "йир", "ky": "Жыл", "ex": "New Year is coming.", "ex_pr": "Нью йир из каминг.", "ex_ky": "Жаңы жыл келе жатат."},
    {"en": "Hour", "pr": "ауэр", "ky": "Саат", "ex": "One hour left.", "ex_pr": "Уан ауэр лефт.", "ex_ky": "Бир саат калды."},
    {"en": "Minute", "pr": "минит", "ky": "Мүнөт", "ex": "Wait a minute.", "ex_pr": "Уэйт э минит.", "ex_ky": "Бир мүнөт күт."},
    {"en": "Second", "pr": "секонд", "ky": "Секунд", "ex": "Just a second.", "ex_pr": "Джаст э секонд.", "ex_ky": "Бир секунд."},
    {"en": "Hello", "pr": "хэлоу", "ky": "Салам", "ex": "Hello, how are you?", "ex_pr": "Хэлоу, хау ар ю?", "ex_ky": "Салам, кандайсың?"},
    {"en": "Goodbye", "pr": "гудбай", "ky": "Кош бол", "ex": "Goodbye, see you later.", "ex_pr": "Гудбай, сии ю лэйтэр.", "ex_ky": "Кош бол, кийин көрүшкөнчө."},
    {"en": "Please", "pr": "плииз", "ky": "Өтүнөм", "ex": "Please help me.", "ex_pr": "Плииз хелп ми.", "ex_ky": "Мага жардам бер."},
    {"en": "Thank you", "pr": "сэнк ю", "ky": "Рахмат", "ex": "Thank you very much.", "ex_pr": "Сэнк ю вэри мач.", "ex_ky": "Чоң рахмат."},
    {"en": "Sorry", "pr": "сори", "ky": "Кечир", "ex": "I am sorry.", "ex_pr": "Ай эм сори.", "ex_ky": "Мен кечирим сурайм."},
    {"en": "Yes", "pr": "йес", "ky": "Ооба", "ex": "Yes, I agree.", "ex_pr": "Йес, ай эгри.", "ex_ky": "Ооба, макулмун."},
    {"en": "No", "pr": "ноу", "ky": "Жок", "ex": "No, thank you.", "ex_pr": "Ноу, сэнк ю.", "ex_ky": "Жок, рахмат."},
    {"en": "Maybe", "pr": "мейби", "ky": "Балким", "ex": "Maybe later.", "ex_pr": "Мейби лэйтэр.", "ex_ky": "Балким кийин."},
    {"en": "Always", "pr": "олуэйз", "ky": "Ар дайым", "ex": "I always smile.", "ex_pr": "Ай олуэйз смайл.", "ex_ky": "Мен ар дайым жылмаям."},
    {"en": "Never", "pr": "невэр", "ky": "Эч качан", "ex": "I never give up.", "ex_pr": "Ай невэр гив ап.", "ex_ky": "Мен эч качан баш тартпайм."},
    {"en": "Sometimes", "pr": "самтаймз", "ky": "Кээде", "ex": "Sometimes I read.", "ex_pr": "Самтаймз ай риид.", "ex_ky": "Кээде мен окуйм."},
    {"en": "Often", "pr": "офэн", "ky": "Көп учурда", "ex": "I often travel.", "ex_pr": "Ай офэн трэвэл.", "ex_ky": "Мен көп учурда саякаттайм."},
    {"en": "Usually", "pr": "южуали", "ky": "Адатта", "ex": "I usually wake up early.", "ex_pr": "Ай южуали вэйк ап эрли.", "ex_ky": "Мен адатта эрте турам."},
    {"en": "Now", "pr": "нау", "ky": "Азыр", "ex": "I am busy now.", "ex_pr": "Ай эм бизи нау.", "ex_ky": "Мен азыр бош эмесмин."},
    {"en": "Then", "pr": "зэн", "ky": "Анда", "ex": "See you then.", "ex_pr": "Сии ю зэн.", "ex_ky": "Анда көрүшкөнчө."},
    {"en": "Before", "pr": "бифо", "ky": "Мурда", "ex": "Before I eat.", "ex_pr": "Бифо ай ит.", "ex_ky": "Мен жегенге чейин."},
    {"en": "After", "pr": "афтэр", "ky": "Кийин", "ex": "After school.", "ex_pr": "Афтэр скуул.", "ex_ky": "Мектептен кийин."},
    {"en": "Today", "pr": "тудей", "ky": "Бүгүн", "ex": "Today is sunny.", "ex_pr": "Тудей из сани.", "ex_ky": "Бүгүн күн ачык."},
    {"en": "Tomorrow", "pr": "тумороу", "ky": "Эртең", "ex": "See you tomorrow.", "ex_pr": "Сии ю тумороу.", "ex_ky": "Эртең көрүшкөнчө."},
    {"en": "Yesterday", "pr": "естэрдей", "ky": "Кечээ", "ex": "Yesterday was fun.", "ex_pr": "Естэрдей уоз фан.", "ex_ky": "Кечээ көңүлдүү болду."},
    {"en": "Up", "pr": "ап", "ky": "Өйдө", "ex": "Look up.", "ex_pr": "Лук ап.", "ex_ky": "Өйдө кара."},
    {"en": "Down", "pr": "даун", "ky": "Төмөн", "ex": "Sit down.", "ex_pr": "Сит даун.", "ex_ky": "Олтур."},
    {"en": "Left", "pr": "лефт", "ky": "Сол", "ex": "Turn left.", "ex_pr": "Тёрн лефт.", "ex_ky": "Солго бурул."},
    {"en": "Right", "pr": "райт", "ky": "Оң", "ex": "Turn right.", "ex_pr": "Тёрн райт.", "ex_ky": "Оңго бурул."},
    {"en": "Near", "pr": "нир", "ky": "Жакын", "ex": "Near the house.", "ex_pr": "Нир зэ хаус.", "ex_ky": "Үйгө жакын."},
    {"en": "Far", "pr": "фар", "ky": "Алыс", "ex": "Far away.", "ex_pr": "Фар эуэй.", "ex_ky": "Алыс жерде."},
    {"en": "Open", "pr": "оупэн", "ky": "Ач", "ex": "Open the door.", "ex_pr": "Оупэн зэ дор.", "ex_ky": "Эшикти ач."},
    {"en": "Close", "pr": "клоуз", "ky": "Жап", "ex": "Close the window.", "ex_pr": "Клоуз зэ уиндоу.", "ex_ky": "Терезени жап."},
    {"en": "Enter", "pr": "энтэр", "ky": "Кир", "ex": "Enter the room.", "ex_pr": "Энтэр зэ руум.", "ex_ky": "Бөлмөгө кир."},
    {"en": "Exit", "pr": "эгзит", "ky": "Чык", "ex": "Exit here.", "ex_pr": "Эгзит хиэр.", "ex_ky": "Бул жерден чык."},
    {"en": "Push", "pr": "пуш", "ky": "Түрт", "ex": "Push the button.", "ex_pr": "Пуш зэ батэн.", "ex_ky": "Баскычты бас."},
    {"en": "Pull", "pr": "пул", "ky": "Тарт", "ex": "Pull the rope.", "ex_pr": "Пул зэ роуп.", "ex_ky": "Арканды тарт."},
    {"en": "Throw", "pr": "сроу", "ky": "Ыргыт", "ex": "Throw the ball.", "ex_pr": "Сроу зэ бол.", "ex_ky": "Топту ыргыт."},
    {"en": "Catch", "pr": "кэч", "ky": "Карма", "ex": "Catch the ball.", "ex_pr": "Кэч зэ бол.", "ex_ky": "Топту карма."},
    {"en": "Give", "pr": "гив", "ky": "Бер", "ex": "Give me water.", "ex_pr": "Гив ми уотер.", "ex_ky": "Мага суу бер."},
    {"en": "Take", "pr": "тэйк", "ky": "Ал", "ex": "Take this.", "ex_pr": "Тэйк зис.", "ex_ky": "Муну ал."},
    {"en": "Bring", "pr": "бринг", "ky": "Алып кел", "ex": "Bring a chair.", "ex_pr": "Бринг э чэр.", "ex_ky": "Орундук алып кел."},
    {"en": "Send", "pr": "сенд", "ky": "Жөнөт", "ex": "Send a message.", "ex_pr": "Сенд э мэссиж.", "ex_ky": "Билдирүү жөнөт."},
    {"en": "Receive", "pr": "рисиив", "ky": "Ал", "ex": "Receive a gift.", "ex_pr": "Рисиив э гифт.", "ex_ky": "Белек ал."},
    {"en": "Keep", "pr": "киип", "ky": "Сакта", "ex": "Keep it safe.", "ex_pr": "Киип ит сэйф.", "ex_ky": "Аны коопсуз сакта."},
    {"en": "Hold", "pr": "хоулд", "ky": "Карма", "ex": "Hold my hand.", "ex_pr": "Хоулд май хэнд.", "ex_ky": "Колумду карма."},
    {"en": "Break", "pr": "брэйк", "ky": "Сындыр", "ex": "Don't break it.", "ex_pr": "Доунт брэйк ит.", "ex_ky": "Аны сындырба."},
    {"en": "Fix", "pr": "фикс", "ky": "Оңдо", "ex": "Fix the car.", "ex_pr": "Фикс зэ каар.", "ex_ky": "Унааны оңдо."},
    {"en": "Build", "pr": "билд", "ky": "Кур", "ex": "Build a house.", "ex_pr": "Билд э хаус.", "ex_ky": "Үй кур."},
    {"en": "Create", "pr": "крииэйт", "ky": "Жарат", "ex": "Create something new.", "ex_pr": "Крииэйт самсинг нью.", "ex_ky": "Жаңы нерсени жарат."},
    {"en": "Change", "pr": "чейнж", "ky": "Өзгөрт", "ex": "Change your mind.", "ex_pr": "Чейнж ёр майнд.", "ex_ky": "Оюңду өзгөрт."},
    {"en": "Choose", "pr": "чууз", "ky": "Танда", "ex": "Choose one.", "ex_pr": "Чууз уан.", "ex_ky": "Бирөөнү танда."},
    {"en": "Decide", "pr": "дисайд", "ky": "Чеч", "ex": "Decide now.", "ex_pr": "Дисайд нау.", "ex_ky": "Азыр чеч."},
    {"en": "Forget", "pr": "форгэт", "ky": "Унут", "ex": "Don't forget me.", "ex_pr": "Доунт форгэт ми.", "ex_ky": "Мени унутпа."},
    {"en": "Remember", "pr": "римэмбэр", "ky": "Эсте", "ex": "Remember this day.", "ex_pr": "Римэмбэр зис дэй.", "ex_ky": "Бул күндү эсте."},
    {"en": "Dream", "pr": "дриим", "ky": "Кыял", "ex": "I have a dream.", "ex_pr": "Ай хэв э дриим.", "ex_ky": "Менин кыялым бар."},
    {"en": "Hope", "pr": "хоуп", "ky": "Үмүт", "ex": "I hope so.", "ex_pr": "Ай хоуп соу.", "ex_ky": "Мен үмүттөнөм."},
    {"en": "Believe", "pr": "билиив", "ky": "Ишен", "ex": "I believe you.", "ex_pr": "Ай билиив ю.", "ex_ky": "Мен сага ишенем."},
    {"en": "Understand", "pr": "андерстэнд", "ky": "Түшүн", "ex": "I understand now.", "ex_pr": "Ай андерстэнд нау.", "ex_ky": "Мен азыр түшүндүм."},
    {"en": "Think", "pr": "синк", "ky": "Ойло", "ex": "Think carefully.", "ex_pr": "Синк кээфуллли.", "ex_ky": "Кунт коюп ойло."},
    {"en": "Know", "pr": "ноу", "ky": "Бил", "ex": "I know the answer.", "ex_pr": "Ай ноу зэ ансэр.", "ex_ky": "Мен жоопту билем."},
    {"en": "Feel", "pr": "фиил", "ky": "Сез", "ex": "I feel good.", "ex_pr": "Ай фиил гуд.", "ex_ky": "Мен өзүмдү жакшы сезем."},
    {"en": "Hear", "pr": "хиэр", "ky": "Ук", "ex": "I hear you.", "ex_pr": "Ай хиэр ю.", "ex_ky": "Мен сени уктум."},
    {"en": "Smell", "pr": "смел", "ky": "Жытта", "ex": "Smell the flower.", "ex_pr": "Смел зэ флауэр.", "ex_ky": "Гүлдү жытта."},
    {"en": "Taste", "pr": "тэйст", "ky": "Даамда", "ex": "Taste the soup.", "ex_pr": "Тэйст зэ сууп.", "ex_ky": "Шорпону даамда."},
    {"en": "Touch", "pr": "тач", "ky": "Тий", "ex": "Touch the screen.", "ex_pr": "Тач зэ скриин.", "ex_ky": "Экранга тий."},
    {"en": "Wash", "pr": "уош", "ky": "Жуу", "ex": "Wash your hands.", "ex_pr": "Уош ёр хэндс.", "ex_ky": "Колуңду жуу."},
    {"en": "Clean", "pr": "клиин", "ky": "Тазала", "ex": "Clean the room.", "ex_pr": "Клиин зэ руум.", "ex_ky": "Бөлмөнү тазала."},
    {"en": "Cook", "pr": "кук", "ky": "Бышыр", "ex": "Cook dinner.", "ex_pr": "Кук динэр.", "ex_ky": "Кечки тамак бышыр."},
    {"en": "Eat", "pr": "иит", "ky": "Же", "ex": "Eat healthy food.", "ex_pr": "Иит хэлси фууд.", "ex_ky": "Пайдалуу тамак же."},
    {"en": "Drink", "pr": "дринк", "ky": "Ич", "ex": "Drink water.", "ex_pr": "Дринк уотер.", "ex_ky": "Суу ич."},
    {"en": "Sleep", "pr": "слиип", "ky": "Укта", "ex": "Sleep well.", "ex_pr": "Слиип уэл.", "ex_ky": "Жакшы укта."},
    {"en": "Wake up", "pr": "вэйк ап", "ky": "Ойгон", "ex": "Wake up early.", "ex_pr": "Вэйк ап эрли.", "ex_ky": "Эрте ойгон."},
    {"en": "Rest", "pr": "рест", "ky": "Эс ал", "ex": "Take a rest.", "ex_pr": "Тэйк э рест.", "ex_ky": "Эс ал."},
    {"en": "Run", "pr": "ран", "ky": "Чурка", "ex": "Run fast.", "ex_pr": "Ран фаст.", "ex_ky": "Тез чурка."},
    {"en": "Walk", "pr": "уок", "ky": "Бас", "ex": "Walk slowly.", "ex_pr": "Уок слоули.", "ex_ky": "Жай бас."},
    {"en": "Jump", "pr": "джамп", "ky": "Секір", "ex": "Jump high.", "ex_pr": "Джамп хай.", "ex_ky": "Бийик секір."},
    {"en": "Sit", "pr": "сит", "ky": "Олтур", "ex": "Sit down.", "ex_pr": "Сит даун.", "ex_ky": "Олтур."},
    {"en": "Stand", "pr": "стэнд", "ky": "Тур", "ex": "Stand up.", "ex_pr": "Стэнд ап.", "ex_ky": "Тур."},
    {"en": "Laugh", "pr": "лаф", "ky": "Күл", "ex": "Laugh out loud.", "ex_pr": "Лаф аут лауд.", "ex_ky": "Бийик үн менен күл."},
    {"en": "Cry", "pr": "край", "ky": "Ыйла", "ex": "Don't cry.", "ex_pr": "Доунт край.", "ex_ky": "Ыйлаба."},
    {"en": "Smile", "pr": "смайл", "ky": "Жылмай", "ex": "Smile often.", "ex_pr": "Смайл офэн.", "ex_ky": "Көп жылмай."},
    {"en": "Help", "pr": "хелп", "ky": "Жардам бер", "ex": "Help me please.", "ex_pr": "Хелп ми плииз.", "ex_ky": "Мага жардам бер."},
    {"en": "Ask", "pr": "аск", "ky": "Сура", "ex": "Ask a question.", "ex_pr": "Аск э квесчен.", "ex_ky": "Суроо бер."},
    {"en": "Answer", "pr": "ансэр", "ky": "Жооп бер", "ex": "Answer me.", "ex_pr": "Ансэр ми.", "ex_ky": "Мага жооп бер."},
    {"en": "Call", "pr": "кол", "ky": "Чакыр", "ex": "Call me later.", "ex_pr": "Кол ми лэйтэр.", "ex_ky": "Мага кийин чалыш."},
    {"en": "Find", "pr": "файнд", "ky": "Тап", "ex": "Find the key.", "ex_pr": "Файнд зэ кии.", "ex_ky": "Ачкычты тап."},
    {"en": "Lose", "pr": "лууз", "ky": "Жогот", "ex": "Don't lose hope.", "ex_pr": "Доунт лууз хоуп.", "ex_ky": "Үмүтүңдү жоготпо."},
    {"en": "Wait", "pr": "уэйт", "ky": "Күт", "ex": "Wait for me.", "ex_pr": "Уэйт фор ми.", "ex_ky": "Мени күт."},
    {"en": "Start", "pr": "старт", "ky": "Башта", "ex": "Start now.", "ex_pr": "Старт нау.", "ex_ky": "Азыр башта."},
    {"en": "Finish", "pr": "финиш", "ky": "Бүтүр", "ex": "Finish your work.", "ex_pr": "Финиш ёр уорк.", "ex_ky": "Жумушуңду бүтүр."},
    {"en": "Stop", "pr": "стоп", "ky": "Токто", "ex": "Stop the car.", "ex_pr": "Стоп зэ каар.", "ex_ky": "Унааны токто."},
    {"en": "Go", "pr": "гоу", "ky": "Бар", "ex": "Go straight.", "ex_pr": "Гоу стрэйт.", "ex_ky": "Түз бар."},
    {"en": "Come", "pr": "кам", "ky": "Кел", "ex": "Come here.", "ex_pr": "Кам хиэр.", "ex_ky": "Бул жакка кел."},
    {"en": "Arrive", "pr": "эрайв", "ky": "Келип жет", "ex": "Arrive on time.", "ex_pr": "Эрайв он тайм.", "ex_ky": "Убагында келип жет."},
    {"en": "Leave", "pr": "лиив", "ky": "Кет", "ex": "Leave now.", "ex_pr": "Лиив нау.", "ex_ky": "Азыр кет."},
    {"en": "Fly", "pr": "флай", "ky": "Уч", "ex": "Birds fly high.", "ex_pr": "Бёрдс флай хай.", "ex_ky": "Куштар бийик учат."},
    {"en": "Swim", "pr": "суим", "ky": "Сүз", "ex": "Fish swim well.", "ex_pr": "Фиш суим уэл.", "ex_ky": "Балыктар жакшы сүзөт."},
    {"en": "Climb", "pr": "клайм", "ky": "Чык", "ex": "Climb the mountain.", "ex_pr": "Клайм зэ маунтин.", "ex_ky": "Тоого чык."},
    {"en": "Fall", "pr": "фол", "ky": "Күл", "ex": "Leaves fall.", "ex_pr": "Лиивз фол.", "ex_ky": "Жалбырактар түшөт."},
    {"en": "Rise", "pr": "райз", "ky": "Көтөрүл", "ex": "The sun rises.", "ex_pr": "Зэ сан райзез.", "ex_ky": "Күн чыгат."},
    {"en": "Live", "pr": "лив", "ky": "Жаша", "ex": "I live here.", "ex_pr": "Ай лив хиэр.", "ex_ky": "Мен бул жерде жашайм."},
    {"en": "Die", "pr": "дай", "ky": "Өл", "ex": "Flowers die.", "ex_pr": "Флауэрз дай.", "ex_ky": "Гүлдөр өлөт."},
    {"en": "Born", "pr": "борн", "ky": "Төрөл", "ex": "I was born here.", "ex_pr": "Ай уоз борн хиэр.", "ex_ky": "Мен бул жерде төрөлгөм."},
    {"en": "Grow", "pr": "гроу", "ky": "Өс", "ex": "Trees grow slow.", "ex_pr": "Трииз гроу слоу.", "ex_ky": "Дарактар жай өсөт."},
    {"en": "Plant", "pr": "плант", "ky": "Отургуз", "ex": "Plant a tree.", "ex_pr": "Плант э трии.", "ex_ky": "Дарак отургуз."},
    {"en": "Cut", "pr": "кат", "ky": "Кес", "ex": "Cut the paper.", "ex_pr": "Кат зэ пэйпэр.", "ex_ky": "Кагазды кес."},
    {"en": "Draw", "pr": "дро", "ky": "Сүрөт тарт", "ex": "Draw a picture.", "ex_pr": "Дро э пикчэр.", "ex_ky": "Сүрөт тарт."},
    {"en": "Paint", "pr": "пейнт", "ky": "Боё", "ex": "Paint the wall.", "ex_pr": "Пейнт зэ уол.", "ex_ky": "Дубалды боё."},
    {"en": "Sing", "pr": "синг", "ky": "Ырда", "ex": "Sing a song.", "ex_pr": "Синг э сонг.", "ex_ky": "Ырда."},
    {"en": "Dance", "pr": "данс", "ky": "Бийле", "ex": "Dance with me.", "ex_pr": "Данс уиз ми.", "ex_ky": "Мени менен бийле."},
    {"en": "Play", "pr": "плэй", "ky": "Ойно", "ex": "Play football.", "ex_pr": "Плэй футбол.", "ex_ky": "Футбол ойно."},
    {"en": "Win", "pr": "уин", "ky": "Ут", "ex": "Win the game.", "ex_pr": "Уин зэ гэйм.", "ex_ky": "Оюнду ут."},
    {"en": "Lose", "pr": "луз", "ky": "Утул", "ex": "Don't lose.", "ex_pr": "Доунт луз.", "ex_ky": "Утулба."},
    {"en": "Fight", "pr": "файт", "ky": "Согуш", "ex": "Fight for peace.", "ex_pr": "Файт фор пиис.", "ex_ky": "Тынчтык үчүн күрөш."},
    {"en": "Win", "pr": "уин", "ky": "Жең", "ex": "Win the match.", "ex_pr": "Уин зэ мэч.", "ex_ky": "Жекени жең."},
    {"en": "Marry", "pr": "мэри", "ky": "Үйлөн", "ex": "They marry.", "ex_pr": "Зэй мэри.", "ex_ky": "Алар үйлөнүшөт."},
    {"en": "Divorce", "pr": "диворс", "ky": "Ажыраш", "ex": "They divorce.", "ex_pr": "Зэй диворс.", "ex_ky": "Алар ажырашышат."},
    {"en": "Meet", "pr": "миит", "ky": "Жолук", "ex": "Meet my friend.", "ex_pr": "Миит май фрэнд.", "ex_ky": "Досум менен жолук."},
    {"en": "Visit", "pr": "визит", "ky": "Бар", "ex": "Visit your parents.", "ex_pr": "Визит ёр пэрэнтс.", "ex_ky": "Ата-энеңе бар."},
    {"en": "Invite", "pr": "инвайт", "ky": "Чакыр", "ex": "Invite friends.", "ex_pr": "Инвайт фрэндс.", "ex_ky": "Досторду чакыр."},
    {"en": "Celebrate", "pr": "селебрэйт", "ky": "Майрамда", "ex": "Celebrate birthday.", "ex_pr": "Селебрэйт бёрсдэй.", "ex_ky": "Туулган күндү майрамда."},
    {"en": "Thank", "pr": "сэнк", "ky": "Рахмат айт", "ex": "Thank God.", "ex_pr": "Сэнк год.", "ex_ky": "Кудайга шүгүр."},
    {"en": "Forgive", "pr": "форгив", "ky": "Кечир", "ex": "Forgive me.", "ex_pr": "Форгив ми.", "ex_ky": "Мени кечир."},
    {"en": "Promise", "pr": "промиc", "ky": "Убада кыл", "ex": "Promise me.", "ex_pr": "Промиc ми.", "ex_ky": "Мага убада кыл."},
    {"en": "Swear", "pr": "суээр", "ky": "Ант бер", "ex": "I swear.", "ex_pr": "Ай суээр.", "ex_ky": "Мен ант берем."},
    {"en": "Wish", "pr": "уиш", "ky": "Тилек кыл", "ex": "Make a wish.", "ex_pr": "Мэйк э уиш.", "ex_ky": "Тилек кыл."},
    {"en": "Want", "pr": "уонт", "ky": "Каала", "ex": "I want water.", "ex_pr": "Ай уонт уотер.", "ex_ky": "Мен суу каалайм."},
    {"en": "Need", "pr": "ниид", "ky": "Керек", "ex": "I need help.", "ex_pr": "Ай ниид хелп.", "ex_ky": "Мага жардам керек."},
    {"en": "Have", "pr": "хэв", "ky": "Бар", "ex": "I have a car.", "ex_pr": "Ай хэв э каар.", "ex_ky": "Менин унаам бар."},
    {"en": "Get", "pr": "гет", "ky": "Ал", "ex": "Get the book.", "ex_pr": "Гет зэ бук.", "ex_ky": "Китепти ал."},
    {"en": "Make", "pr": "мэйк", "ky": "Жаса", "ex": "Make coffee.", "ex_pr": "Мэйк кофи.", "ex_ky": "Кофе жаса."},
    {"en": "Do", "pr": "ду", "ky": "Кыл", "ex": "Do homework.", "ex_pr": "Ду хоумворк.", "ex_ky": "Үй тапшырмасын кыл."},
    {"en": "Be", "pr": "би", "ky": "Бол", "ex": "Be happy.", "ex_pr": "Би хэпи.", "ex_ky": "Бактылуу бол."},
    {"en": "Can", "pr": "кэн", "ky": "Ала", "ex": "I can do it.", "ex_pr": "Ай кэн ду ит.", "ex_ky": "Мен аны жасай алам."},
    {"en": "Must", "pr": "маст", "ky": "Керек", "ex": "You must go.", "ex_pr": "Ю маст гоу.", "ex_ky": "Сен барышың керек."},
    {"en": "Should", "pr": "шуд", "ky": "Керек", "ex": "You should sleep.", "ex_pr": "Ю шуд слиип.", "ex_ky": "Сен укташың керек."},
    {"en": "Would", "pr": "вуд", "ky": "Эле", "ex": "I would like tea.", "ex_pr": "Ай вуд лайк тии.", "ex_ky": "Мен чай ичмекчимин."},
    {"en": "Could", "pr": "куд", "ky": "Ала", "ex": "I could help.", "ex_pr": "Ай куд хелп.", "ex_ky": "Мен жардам бере алам."},
    {"en": "May", "pr": "мэй", "ky": "Болот", "ex": "May I come?", "ex_pr": "Мэй ай кам?", "ex_ky": "Кирсем болобу?"},
    {"en": "Might", "pr": "майт", "ky": "Балким", "ex": "I might go.", "ex_pr": "Ай майт гоу.", "ex_ky": "Мен барармын."},
    {"en": "Shall", "pr": "шэл", "ky": "Керек", "ex": "Shall we go?", "ex_pr": "Шэл уи гоу?", "ex_ky": "Барабызбы?"},
    {"en": "Will", "pr": "уил", "ky": "Болот", "ex": "I will come.", "ex_pr": "Ай уил кам.", "ex_ky": "Мен келем."},
    {"en": "Shall", "pr": "шэл", "ky": "Керек", "ex": "Shall I open?", "ex_pr": "Шэл ай оупэн?", "ex_ky": "Ачсамбы?"},
    {"en": "Used to", "pr": "юст ту", "ky": "Эле", "ex": "I used to play.", "ex_pr": "Ай юст ту плэй.", "ex_ky": "Мен ойноп жүрчүмүн."},
    {"en": "One", "pr": "уан", "ky": "Бир", "ex": "One apple.", "ex_pr": "Уан эпл.", "ex_ky": "Бир алма."},
    {"en": "Two", "pr": "ту", "ky": "Эки", "ex": "Two hands.", "ex_pr": "Ту хэндс.", "ex_ky": "Эки кол."},
    {"en": "Three", "pr": "сри", "ky": "Үч", "ex": "Three birds.", "ex_pr": "Сри бёрдс.", "ex_ky": "Үч куш."},
    {"en": "Four", "pr": "фор", "ky": "Төрт", "ex": "Four seasons.", "ex_pr": "Фор сиизонс.", "ex_ky": "Төрт мезгил."},
    {"en": "Five", "pr": "файв", "ky": "Беш", "ex": "Five fingers.", "ex_pr": "Файв фингэрс.", "ex_ky": "Беш манжа."},
    {"en": "Six", "pr": "сикс", "ky": "Алты", "ex": "Six eggs.", "ex_pr": "Сикс эгз.", "ex_ky": "Алты жумуртка."},
    {"en": "Seven", "pr": "сэвэн", "ky": "Жети", "ex": "Seven days.", "ex_pr": "Сэвэн дэйз.", "ex_ky": "Жети күн."},
    {"en": "Eight", "pr": "эйт", "ky": "Сегиз", "ex": "Eight legs.", "ex_pr": "Эйт легз.", "ex_ky": "Сегиз бут."},
    {"en": "Nine", "pr": "найн", "ky": "Тогуз", "ex": "Nine lives.", "ex_pr": "Найн ливз.", "ex_ky": "Тогуз жашоо."},
    {"en": "Ten", "pr": "тэн", "ky": "Он", "ex": "Ten years.", "ex_pr": "Тэн йирс.", "ex_ky": "Он жыл."},
    {"en": "Hundred", "pr": "хандред", "ky": "Жүз", "ex": "One hundred.", "ex_pr": "Уан хандред.", "ex_ky": "Бир жүз."},
    {"en": "Thousand", "pr": "саузэнд", "ky": "Миң", "ex": "One thousand.", "ex_pr": "Уан саузэнд.", "ex_ky": "Бир миң."},
    {"en": "First", "pr": "фёст", "ky": "Биринчи", "ex": "First place.", "ex_pr": "Фёст плэйс.", "ex_ky": "Биринчи орун."},
    {"en": "Second", "pr": "секонд", "ky": "Экинчи", "ex": "Second time.", "ex_pr": "Секонд тайм.", "ex_ky": "Экинчи жолу."},
    {"en": "Third", "pr": "сёрд", "ky": "Үчүнчү", "ex": "Third person.", "ex_pr": "Сёрд пёрсэн.", "ex_ky": "Үчүнчү адам."},
    {"en": "Last", "pr": "ласт", "ky": "Акыркы", "ex": "Last chance.", "ex_pr": "Ласт чанс.", "ex_ky": "Акыркы мүмкүнчүлүк."},
    {"en": "Next", "pr": "некст", "ky": "Кийинки", "ex": "Next week.", "ex_pr": "Некст уиик.", "ex_ky": "Кийинки апта."},
    {"en": "Same", "pr": "сэйм", "ky": "Ошол эле", "ex": "Same thing.", "ex_pr": "Сэйм синг.", "ex_ky": "Ошол эле нерсе."},
    {"en": "Different", "pr": "дифрэнт", "ky": "Башкача", "ex": "Different color.", "ex_pr": "Дифрэнт колэр.", "ex_ky": "Башкача түс."},
    {"en": "Own", "pr": "оун", "ky": "Өз", "ex": "My own car.", "ex_pr": "Май оун каар.", "ex_ky": "Менин өз унаам."},
    {"en": "Other", "pr": "азэр", "ky": "Башка", "ex": "Other people.", "ex_pr": "Азэр пиипл.", "ex_ky": "Башка адамдар."},
    {"en": "Another", "pr": "эназэр", "ky": "Дагы бир", "ex": "Another chance.", "ex_pr": "Эназэр чанс.", "ex_ky": "Дагы бир мүмкүнчүлүк."},
    {"en": "Both", "pr": "боус", "ky": "Экөө", "ex": "Both hands.", "ex_pr": "Боус хэндс.", "ex_ky": "Эки кол тең."},
    {"en": "All", "pr": "ол", "ky": "Баары", "ex": "All people.", "ex_pr": "Ол пиипл.", "ex_ky": "Бардык адамдар."},
    {"en": "Some", "pr": "сам", "ky": "Бир аз", "ex": "Some water.", "ex_pr": "Сам уотер.", "ex_ky": "Бир аз суу."},
    {"en": "Any", "pr": "эни", "ky": "Кандайдыр", "ex": "Any idea?", "ex_pr": "Эни айдиа?", "ex_ky": "Кандайдыр ой барбы?"},
    {"en": "No", "pr": "ноу", "ky": "Жок", "ex": "No problem.", "ex_pr": "Ноу проблэм.", "ex_ky": "Көйгөй жок."},
    {"en": "Every", "pr": "эври", "ky": "Ар бир", "ex": "Every day.", "ex_pr": "Эври дэй.", "ex_ky": "Ар күнү."},
    {"en": "Each", "pr": "иич", "ky": "Ар бир", "ex": "Each person.", "ex_pr": "Иич пёрсэн.", "ex_ky": "Ар бир адам."},
    {"en": "Either", "pr": "айзэр", "ky": "Же", "ex": "Either way.", "ex_pr": "Айзэр уэй.", "ex_ky": "Кандай болсо да."},
    {"en": "Neither", "pr": "найзэр", "ky": "Эч бири", "ex": "Neither one.", "ex_pr": "Найзэр уан.", "ex_ky": "Эч бири."},
    {"en": "So", "pr": "соу", "ky": "Ошондуктан", "ex": "So beautiful.", "ex_pr": "Соу бьютифул.", "ex_ky": "Өтө кооз."},
    {"en": "Very", "pr": "вэри", "ky": "Өтө", "ex": "Very good.", "ex_pr": "Вэри гуд.", "ex_ky": "Өтө жакшы."},
    {"en": "Too", "pr": "ту", "ky": "Да", "ex": "Me too.", "ex_pr": "Ми ту.", "ex_ky": "Мен да."},
    {"en": "Also", "pr": "олсоу", "ky": "Ошондой эле", "ex": "I also came.", "ex_pr": "Ай олсоу кэйм.", "ex_ky": "Мен да келдим."},
    {"en": "Only", "pr": "оунли", "ky": "Ганала", "ex": "Only one.", "ex_pr": "Оунли уан.", "ex_ky": "Бир гана."},
    {"en": "Just", "pr": "джаст", "ky": "Так", "ex": "Just now.", "ex_pr": "Джаст нау.", "ex_ky": "Так азыр."},
    {"en": "Even", "pr": "иивэн", "ky": "Да", "ex": "Even me.", "ex_pr": "Иивэн ми.", "ex_ky": "Мен да."},
    {"en": "Really", "pr": "риэли", "ky": "Чындап", "ex": "Really good.", "ex_pr": "Риэли гуд.", "ex_ky": "Чындап жакшы."},
    {"en": "Very", "pr": "вэри", "ky": "Абдан", "ex": "Very nice.", "ex_pr": "Вэри найс.", "ex_ky": "Абдан жакшы."},
    {"en": "Quite", "pr": "квайт", "ky": "Орточо", "ex": "Quite good.", "ex_pr": "Квайт гуд.", "ex_ky": "Орточо жакшы."},
    {"en": "Almost", "pr": "олмоуст", "ky": "Дээрлик", "ex": "Almost done.", "ex_pr": "Олмоуст дан.", "ex_ky": "Дээрлик бүттү."},
    {"en": "Already", "pr": "олрэди", "ky": "Буга чейин", "ex": "Already finished.", "ex_pr": "Олрэди финишт.", "ex_ky": "Буга чейин бүткөн."},
    {"en": "Still", "pr": "стил", "ky": "Дагы", "ex": "Still waiting.", "ex_pr": "Стил уэйтинг.", "ex_ky": "Дагы күтүүдө."},
    {"en": "Yet", "pr": "йет", "ky": "Али", "ex": "Not yet.", "ex_pr": "Нот йет.", "ex_ky": "Али эмес."},
    {"en": "Again", "pr": "эгэн", "ky": "Кайра", "ex": "Again please.", "ex_pr": "Эгэн плииз.", "ex_ky": "Кайра өтүнөм."},
    {"en": "Always", "pr": "олуэйз", "ky": "Дайыма", "ex": "Always late.", "ex_pr": "Олуэйз лэйт.", "ex_ky": "Дайыма кеч."},
    {"en": "Never", "pr": "невэр", "ky": "Эч качан", "ex": "Never mind.", "ex_pr": "Невэр майнд.", "ex_ky": "Эч нерсе эмес."},
    {"en": "Often", "pr": "офэн", "ky": "Көп", "ex": "Often visit.", "ex_pr": "Офэн визит.", "ex_ky": "Көп барат."},
    {"en": "Sometimes", "pr": "самтаймз", "ky": "Кээде", "ex": "Sometimes happy.", "ex_pr": "Самтаймз хэпи.", "ex_ky": "Кээде бактылуу."},
    {"en": "Usually", "pr": "южуали", "ky": "Адатта", "ex": "Usually early.", "ex_pr": "Южуали эрли.", "ex_ky": "Адатта эрте."},
    {"en": "Seldom", "pr": "сэлдэм", "ky": "Сейрек", "ex": "Seldom seen.", "ex_pr": "Сэлдэм сиин.", "ex_ky": "Сейрек кездешет."},
    {"en": "Rarely", "pr": "рэрли", "ky": "Сейрек", "ex": "Rarely late.", "ex_pr": "Рэрли лэйт.", "ex_ky": "Сейрек кечиккен."},
    {"en": "Quickly", "pr": "квикли", "ky": "Тез", "ex": "Run quickly.", "ex_pr": "Ран квикли.", "ex_ky": "Тез чурка."},
    {"en": "Slowly", "pr": "слоули", "ky": "Жай", "ex": "Walk slowly.", "ex_pr": "Уок слоули.", "ex_ky": "Жай бас."},
    {"en": "Carefully", "pr": "кээфули", "ky": "Кунт коюп", "ex": "Listen carefully.", "ex_pr": "Лисэн кээфули.", "ex_ky": "Кунт коюп угу."},
    {"en": "Easily", "pr": "изили", "ky": "Оңой", "ex": "Easily done.", "ex_pr": "Изили дан.", "ex_ky": "Оңой жасалды."},
    {"en": "Hardly", "pr": "хардли", "ky": "Кыйын", "ex": "Hardly working.", "ex_pr": "Хардли уоркинг.", "ex_ky": "Кыйын иштеп."},
    {"en": "Nearly", "pr": "нирли", "ky": "Дээрлик", "ex": "Nearly there.", "ex_pr": "Нирли зээр.", "ex_ky": "Дээрлик жеттик."},
    {"en": "Exactly", "pr": "игзэктли", "ky": "Так", "ex": "Exactly right.", "ex_pr": "Игзэктли райт.", "ex_ky": "Так туура."},
    {"en": "Probably", "pr": "пробэбли", "ky": "Балким", "ex": "Probably yes.", "ex_pr": "Пробэбли йес.", "ex_ky": "Балким ооба."},
    {"en": "Certainly", "pr": "сёртэнли", "ky": "Албетте", "ex": "Certainly not.", "ex_pr": "Сёртэнли нот.", "ex_ky": "Албетте жок."},
    {"en": "Maybe", "pr": "мейби", "ky": "Балким", "ex": "Maybe later.", "ex_pr": "Мейби лэйтэр.", "ex_ky": "Балким кийин."},
    {"en": "Perhaps", "pr": "пёрхэпс", "ky": "Балким", "ex": "Perhaps tomorrow.", "ex_pr": "Пёрхэпс тумороу.", "ex_ky": "Балким эртең."},
    {"en": "Together", "pr": "тугэзэр", "ky": "Чогуу", "ex": "Together forever.", "ex_pr": "Тугэзэр форэвэр.", "ex_ky": "Түбөлүккө чогуу."},
    {"en": "Alone", "pr": "элоун", "ky": "Жалгыз", "ex": "All alone.", "ex_pr": "Ол элоун.", "ex_ky": "Так жалгыз."},
    {"en": "Apart", "pr": "эпарт", "ky": "Бөлүнүп", "ex": "Grow apart.", "ex_pr": "Гроу эпарт.", "ex_ky": "Бөлүнүп өсүү."},
    {"en": "Together", "pr": "тугэзэр", "ky": "Бирге", "ex": "Together we stand.", "ex_pr": "Тугэзэр уи стэнд.", "ex_ky": "Бирге турабыз."}
];
