const numbers = [
    {"en": "One", "pr": "уан", "ky": "Бир", "ex": "I have one brother.", "ex_pr": "Ай хэв уан бразэр.", "ex_ky": "Менин бир бир тууганым бар."},
    {"en": "Two", "pr": "ту", "ky": "Эки", "ex": "I need two apples.", "ex_pr": "Ай нид ту эплс.", "ex_ky": "Мага эки алма керек."},
    {"en": "Three", "pr": "сри", "ky": "Үч", "ex": "Three cats are playing.", "ex_pr": "Сри кэтс ар плэйинг.", "ex_ky": "Үч мышык ойнап жатат."},
    {"en": "Four", "pr": "фор", "ky": "Төрт", "ex": "Four seasons in a year.", "ex_pr": "Фор сизонз ин э йир.", "ex_ky": "Жылда төрт мезгил."},
    {"en": "Five", "pr": "файв", "ky": "Беш", "ex": "I have five fingers.", "ex_pr": "Ай хэв файв финггэрс.", "ex_ky": "Менин беш манжам бар."},
    {"en": "Six", "pr": "сикс", "ky": "Алты", "ex": "Six eggs in the basket.", "ex_pr": "Сикс эгз ин зэ баскит.", "ex_ky": "Себетте алты жумуртка."},
    {"en": "Seven", "pr": "сэвэн", "ky": "Жети", "ex": "Seven days in a week.", "ex_pr": "Сэвэн дэйз ин э уик.", "ex_ky": "Аптада жети күн."},
    {"en": "Eight", "pr": "эйт", "ky": "Сегиз", "ex": "Eight planets in solar system.", "ex_pr": "Эйт плэнэтс ин соулэр систим.", "ex_ky": "Күн системасында сегиз планета."},
    {"en": "Nine", "pr": "найн", "ky": "Тогуз", "ex": "Nine lives of a cat.", "ex_pr": "Найн лайвз ов э кэт.", "ex_ky": "Мышыктын тогуз жаны."},
    {"en": "Ten", "pr": "тэн", "ky": "Он", "ex": "Ten fingers on your hands.", "ex_pr": "Тэн финггэрз он ёр хэндз.", "ex_ky": "Колдоруңузда он манжа."},
    {"en": "Eleven", "pr": "илэвэн", "ky": "Он бир", "ex": "Eleven players on a team.", "ex_pr": "Илэвэн плэйэрс он э тим.", "ex_ky": "Командада он бир оюнчу."},
    {"en": "Twelve", "pr": "туэлв", "ky": "Он эки", "ex": "Twelve months in a year.", "ex_pr": "Туэлв манс ин э йир.", "ex_ky": "Жылда он эки ай."},
    {"en": "Thirteen", "pr": "сёртин", "ky": "Он үч", "ex": "Thirteen is a lucky number.", "ex_pr": "Сёртин из э лаки намбэр.", "ex_ky": "Он үч бактылуу сан."},
    {"en": "Fourteen", "pr": "фортин", "ky": "Он төрт", "ex": "Fourteen days quarantine.", "ex_pr": "Фортин дэйз куорантин.", "ex_ky": "Он төрт күн карантин."},
    {"en": "Fifteen", "pr": "фифтин", "ky": "Он беш", "ex": "Fifteen minutes of fame.", "ex_pr": "Фифтин минут ов фэйм.", "ex_ky": "Он беш мүнөт атактуулук."},
    {"en": "Sixteen", "pr": "сикстин", "ky": "Он алты", "ex": "Sweet sixteen birthday.", "ex_pr": "Суит сикстин бёрсдэй.", "ex_ky": "Он алты жас майрамы."},
    {"en": "Seventeen", "pr": "сэвэнтин", "ky": "Он жети", "ex": "Seventeen years old.", "ex_pr": "Сэвэнтин йирз олд.", "ex_ky": "Он жети жашта."},
    {"en": "Eighteen", "pr": "эйтин", "ky": "Он сегиз", "ex": "Eighteen is adult age.", "ex_pr": "Эйтин из эдалт эйж.", "ex_ky": "Он сегиз чоңойгон жаш."},
    {"en": "Nineteen", "pr": "найтин", "ky": "Он тогуз", "ex": "Nineteen ninety nine.", "ex_pr": "Найтин наинти найн.", "ex_ky": "Тогуз жүз токсон тогуз."},
    {"en": "Twenty", "pr": "туэнти", "ky": "Жыйырма", "ex": "Twenty dollars in my pocket.", "ex_pr": "Туэнти долларз ин май покит.", "ex_ky": "Чөнтөгүмдө жыйырма доллар."},
    {"en": "Twenty one", "pr": "туэнти уан", "ky": "Жыйырма бир", "ex": "Twenty one is my age.", "ex_pr": "Туэнти уан из май эйж.", "ex_ky": "Жыйырма бир менин жашым."},
    {"en": "Twenty two", "pr": "туэнти ту", "ky": "Жыйырма эки", "ex": "Twenty two degrees Celsius.", "ex_pr": "Туэнти ту дигриз сэлсиус.", "ex_ky": "Жыйырма эки градус ысык."},
    {"en": "Twenty three", "pr": "туэнти сри", "ky": "Жыйырма үч", "ex": "Twenty three is prime number.", "ex_pr": "Туэнти сри из прайм намбэр.", "ex_ky": "Жыйырма үч жөнөкөй сан."},
    {"en": "Twenty four", "pr": "туэнти фор", "ky": "Жыйырма төрт", "ex": "Twenty four hours in a day.", "ex_pr": "Туэнти фор ауэрз ин э дэй.", "ex_ky": "Суткада жыйырма төрт саат."},
    {"en": "Twenty five", "pr": "туэнти файв", "ky": "Жыйырма беш", "ex": "Twenty five cents.", "ex_pr": "Туэнти файв сэнтс.", "ex_ky": "Жыйырма беш цент."},
    {"en": "Twenty six", "pr": "туэнти сикс", "ky": "Жыйырма алты", "ex": "Twenty six letters in alphabet?", "ex_pr": "Туэнти сикс летэрз ин элфэбэт?", "ex_ky": "Алиппеде жыйырма алты тамга?"},
    {"en": "Twenty seven", "pr": "туэнти сэвэн", "ky": "Жыйырма жети", "ex": "Twenty seven is cube of three.", "ex_pr": "Туэнти сэвэн из кьюб ов сри.", "ex_ky": "Жыйырма жети - үчтүн кубу."},
    {"en": "Twenty eight", "pr": "туэнти эйт", "ky": "Жыйырма сегиз", "ex": "Twenty eight days in February.", "ex_pr": "Туэнти эйт дэйз ин фэбруэри.", "ex_ky": "Февралда жыйырма сегиз күн."},
    {"en": "Twenty nine", "pr": "туэнти найн", "ky": "Жыйырма тогуз", "ex": "Twenty nine is my house number.", "ex_pr": "Туэнти найн из май хаус намбэр.", "ex_ky": "Жыйырма тогуз менин үй номерым."},
    {"en": "Thirty", "pr": "сёрти", "ky": "Отуз", "ex": "Thirty minutes of exercise.", "ex_pr": "Сёрти минут ов эксэрсайз.", "ex_ky": "Отуз мүнөт көнүгүү."},
    {"en": "Thirty one", "pr": "сёрти уан", "ky": "Отуз бир", "ex": "Thirty one days in January.", "ex_pr": "Сёрти уан дэйз ин джэнюэри.", "ex_ky": "Январда отуз бир күн."},
    {"en": "Thirty two", "pr": "сёрти ту", "ky": "Отуз эки", "ex": "Thirty two teeth for adult.", "ex_pr": "Сёрти ту тис фор эдалт.", "ex_ky": "Чоң кишиде отуз эки тиш."},
    {"en": "Thirty three", "pr": "сёрти сри", "ky": "Отуз үч", "ex": "Thirty three years old Jesus.", "ex_pr": "Сёрти сри йирз олд жизос.", "ex_ky": "Отуз үч жашта Ыйса."},
    {"en": "Thirty four", "pr": "сёрти фор", "ky": "Отуз төрт", "ex": "Thirty four is my lucky number.", "ex_pr": "Сёрти фор из май лаки намбэр.", "ex_ky": "Отуз төрт менин бактылуу саным."},
    {"en": "Thirty five", "pr": "сёрти файв", "ky": "Отуз беш", "ex": "Thirty five millimeters.", "ex_pr": "Сёрти файв миллимитэрз.", "ex_ky": "Отуз беш миллиметр."},
    {"en": "Thirty six", "pr": "сёрти сикс", "ky": "Отуз алты", "ex": "Thirty six degrees.", "ex_pr": "Сёрти сикс дигриз.", "ex_ky": "Отуз алты градус."},
    {"en": "Thirty seven", "pr": "сёрти сэвэн", "ky": "Отуз жети", "ex": "Thirty seven percent.", "ex_pr": "Сёрти сэвэн пэсэнт.", "ex_ky": "Отуз жети процент."},
    {"en": "Thirty eight", "pr": "сёрти эйт", "ky": "Отуз сегиз", "ex": "Thirty eight special.", "ex_pr": "Сёрти эйт спэшл.", "ex_ky": "Отуз сегиз өзгөчө."},
    {"en": "Thirty nine", "pr": "сёрти найн", "ky": "Отуз тогуз", "ex": "Thirty nine steps.", "ex_pr": "Сёрти найн стэпс.", "ex_ky": "Отуз тогуз кадам."},
    {"en": "Forty", "pr": "фоти", "ky": "Кырк", "ex": "Forty winks (short nap).", "ex_pr": "Фоти уинкс (шорт нэп).", "ex_ky": "Кырк көз ирмем (кыска уйку)."},
    {"en": "Forty one", "pr": "фоти уан", "ky": "Кырк бир", "ex": "Forty one kilograms.", "ex_pr": "Фоти уан килограмз.", "ex_ky": "Кырк бир килограмм."},
    {"en": "Forty two", "pr": "фоти ту", "ky": "Кырк эки", "ex": "The answer is forty two.", "ex_pr": "Зэ ансэр из фоти ту.", "ex_ky": "Жооп кырк эки."},
    {"en": "Forty three", "pr": "фоти сри", "ky": "Кырк үч", "ex": "Forty three soldiers.", "ex_pr": "Фоти сри соулджэрз.", "ex_ky": "Кырк үч жоокер."},
    {"en": "Forty four", "pr": "фоти фор", "ky": "Кырк төрт", "ex": "Forty four rpm record.", "ex_pr": "Фоти фор ар пи эм рэкорд.", "ex_ky": "Кырк төрт rpm жазуусу."},
    {"en": "Forty five", "pr": "фоти файв", "ky": "Кырк беш", "ex": "Forty five minutes break.", "ex_pr": "Фоти файв минут брэйк.", "ex_ky": "Кырк беш мүнөт тыныгуу."},
    {"en": "Forty six", "pr": "фоти сикс", "ky": "Кырк алты", "ex": "Forty six thousand.", "ex_pr": "Фоти сикс саузэнд.", "ex_ky": "Кырк алты миң."},
    {"en": "Forty seven", "pr": "фоти сэвэн", "ky": "Кырк жети", "ex": "Forty seven percent of people.", "ex_pr": "Фоти сэвэн пэсэнт ов пипл.", "ex_ky": "Адамдардын кырк жети проценти."},
    {"en": "Forty eight", "pr": "фоти эйт", "ky": "Кырк сегиз", "ex": "Forty eight hours of work.", "ex_pr": "Фоти эйт ауэрз ов уорк.", "ex_ky": "Кырк сегиз саат жумуш."},
    {"en": "Forty nine", "pr": "фоти найн", "ky": "Кырк тогуз", "ex": "Forty nine dollars.", "ex_pr": "Фоти найн долларз.", "ex_ky": "Кырк тогуз доллар."},
    {"en": "Fifty", "pr": "фифти", "ky": "Элүү", "ex": "Fifty years of marriage.", "ex_pr": "Фифти йирз ов мэридж.", "ex_ky": "Элүү жылдык нике."},
    {"en": "Fifty one", "pr": "фифти уан", "ky": "Элүү бир", "ex": "Fifty one acres of land.", "ex_pr": "Фифти уан эйкэрз ов лэнд.", "ex_ky": "Элүү бир акр жер."},
    {"en": "Fifty two", "pr": "фифти ту", "ky": "Элүү эки", "ex": "Fifty two weeks in a year.", "ex_pr": "Фифти ту уикс ин э йир.", "ex_ky": "Жылда элүү эки апта."},
    {"en": "Fifty three", "pr": "фифти сри", "ky": "Элүү үч", "ex": "Fifty three passengers.", "ex_pr": "Фифти сри пэсэнжэрз.", "ex_ky": "Элүү үч жүргүнчү."},
    {"en": "Fifty four", "pr": "фифти фор", "ky": "Элүү төрт", "ex": "Fifty four cards.", "ex_pr": "Фифти фор кардс.", "ex_ky": "Элүү төрт карта."},
    {"en": "Fifty five", "pr": "фифти файв", "ky": "Элүү беш", "ex": "Fifty five miles per hour.", "ex_pr": "Фифти файв майлз пэр ауэр.", "ex_ky": "Саатына элүү беш миль."},
    {"en": "Fifty six", "pr": "фифти сикс", "ky": "Элүү алты", "ex": "Fifty six channels.", "ex_pr": "Фифти сикс чэнэлз.", "ex_ky": "Элүү алты канал."},
    {"en": "Fifty seven", "pr": "фифти сэвэн", "ky": "Элүү жети", "ex": "Fifty seven varieties.", "ex_pr": "Фифти сэвэн вэрайэтиз.", "ex_ky": "Элүү жети түр."},
    {"en": "Fifty eight", "pr": "фифти эйт", "ky": "Элүү сегиз", "ex": "Fifty eight seconds.", "ex_pr": "Фифти эйт сэкондс.", "ex_ky": "Элүү сегиз секунд."},
    {"en": "Fifty nine", "pr": "фифти найн", "ky": "Элүү тогуз", "ex": "Fifty nine cents.", "ex_pr": "Фифти найн сэнтс.", "ex_ky": "Элүү тогуз цент."},
    {"en": "Sixty", "pr": "сиксти", "ky": "Алтымыш", "ex": "Sixty minutes in an hour.", "ex_pr": "Сиксти минут ин эн ауэр.", "ex_ky": "Бир саатта алтымыш мүнөт."},
    {"en": "Sixty one", "pr": "сиксти уан", "ky": "Алтымыш бир", "ex": "Sixty one grams.", "ex_pr": "Сиксти уан грэмз.", "ex_ky": "Алтымыш бир грамм."},
    {"en": "Sixty two", "pr": "сиксти ту", "ky": "Алтымыш эки", "ex": "Sixty two percent of water.", "ex_pr": "Сиксти ту пэсэнт ов уотэр.", "ex_ky": "Суунун алтымыш эки проценти."},
    {"en": "Sixty three", "pr": "сиксти сри", "ky": "Алтымыш үч", "ex": "Sixty three million.", "ex_pr": "Сиксти сри миллион.", "ex_ky": "Алтымыш үч миллион."},
    {"en": "Sixty four", "pr": "сиксти фор", "ky": "Алтымыш төрт", "ex": "Sixty four squares on chessboard.", "ex_pr": "Сиксти фор сквэарз он чесборд.", "ex_ky": "Шахмат тактасында алтымыш төрт чарчы."},
    {"en": "Sixty five", "pr": "сиксти файв", "ky": "Алтымыш беш", "ex": "Sixty five is retirement age.", "ex_pr": "Сиксти файв из ритайэрмэнт эйж.", "ex_ky": "Алтымыш беш - пенсия жашы."},
    {"en": "Sixty six", "pr": "сиксти сикс", "ky": "Алтымыш алты", "ex": "Sixty six route highway.", "ex_pr": "Сиксти сикс рут хайуэй.", "ex_ky": "Алтымыш алтынчы трасса."},
    {"en": "Sixty seven", "pr": "сиксти сэвэн", "ky": "Алтымыш жети", "ex": "Sixty seven kilometers.", "ex_pr": "Сиксти сэвэн киломитэрз.", "ex_ky": "Алтымыш жети километр."},
    {"en": "Sixty eight", "pr": "сиксти эйт", "ky": "Алтымыш сегиз", "ex": "Sixty eight medals won.", "ex_pr": "Сиксти эйт мэдлз уан.", "ex_ky": "Алтымыш сегиз медаль утуп алды."},
    {"en": "Sixty nine", "pr": "сиксти найн", "ky": "Алтымыш тогуз", "ex": "Sixty nine is my favorite.", "ex_pr": "Сиксти найн из май фэйворит.", "ex_ky": "Алтымыш тогуз менин сүйүктүүм."},
    {"en": "Seventy", "pr": "сэвэнти", "ky": "Жетимиш", "ex": "Seventy is the new fifty.", "ex_pr": "Сэвэнти из зэ нью фифти.", "ex_ky": "Жетимиш - жаңы элүү."},
    {"en": "Seventy one", "pr": "сэвэнти уан", "ky": "Жетимиш бир", "ex": "Seventy one pages.", "ex_pr": "Сэвэнти уан пэйжиз.", "ex_ky": "Жетимиш бир барак."},
    {"en": "Seventy two", "pr": "сэвэнти ту", "ky": "Жетимиш эки", "ex": "Seventy two virgins myth.", "ex_pr": "Сэвэнти ту вёрджинз миф.", "ex_ky": "Жетимиш эки кыз уламышы."},
    {"en": "Seventy three", "pr": "сэвэнти сри", "ky": "Жетимиш үч", "ex": "Seventy three percent of Earth.", "ex_pr": "Сэвэнти сри пэсэнт оф Эрс.", "ex_ky": "Жердин жетимиш үч проценти."},
    {"en": "Seventy four", "pr": "сэвэнти фор", "ky": "Жетимиш төрт", "ex": "Seventy four inches.", "ex_pr": "Сэвэнти фор инчэз.", "ex_ky": "Жетимиш төрт дюйм."},
    {"en": "Seventy five", "pr": "сэвэнти файв", "ky": "Жетимиш беш", "ex": "Seventy five cents per minute.", "ex_pr": "Сэвэнти файв сэнтс пэр минут.", "ex_ky": "Мүнөтүнө жетимиш беш цент."},
    {"en": "Seventy six", "pr": "сэвэнти сикс", "ky": "Жетимиш алты", "ex": "Seventy six trombones song.", "ex_pr": "Сэвэнти сикс тромбоунз сонг.", "ex_ky": "Жетимиш алты тромбон ыры."},
    {"en": "Seventy seven", "pr": "сэвэнти сэвэн", "ky": "Жетимиш жети", "ex": "Seventy seven percent of success.", "ex_pr": "Сэвэнти сэвэн пэсэнт ов саксес.", "ex_ky": "Ийгиликтин жетимиш жети проценти."},
    {"en": "Seventy eight", "pr": "сэвэнти эйт", "ky": "Жетимиш сегиз", "ex": "Seventy eight records vinyl.", "ex_pr": "Сэвэнти эйт рэкордс вайнил.", "ex_ky": "Жетимиш сегиз винил жазуусу."},
    {"en": "Seventy nine", "pr": "сэвэнти найн", "ky": "Жетимиш тогуз", "ex": "Seventy nine dollars for ticket.", "ex_pr": "Сэвэнти найн долларз фор тикит.", "ex_ky": "Билетке жетимиш тогуз доллар."},
    {"en": "Eighty", "pr": "эйти", "ky": "Сексен", "ex": "Eighty percent of success is showing up.", "ex_pr": "Эйти пэсэнт ов саксес из шоуинг ап.", "ex_ky": "Ийгиликтин сексени пайда болуу."},
    {"en": "Eighty one", "pr": "эйти уан", "ky": "Сексен бир", "ex": "Eighty one thousand words.", "ex_pr": "Эйти уан саузэнд уордз.", "ex_ky": "Сексен бир миң сөз."},
    {"en": "Eighty two", "pr": "эйти ту", "ky": "Сексен эки", "ex": "Eighty two percent of statistics.", "ex_pr": "Эйти ту пэсэнт ов стэтистикс.", "ex_ky": "Статистиканын сексен эки проценти."},
    {"en": "Eighty three", "pr": "эйти сри", "ky": "Сексен үч", "ex": "Eighty three meters high.", "ex_pr": "Эйти сри митэрз хай.", "ex_ky": "Сексен үч метр бийик."},
    {"en": "Eighty four", "pr": "эйти фор", "ky": "Сексен төрт", "ex": "Eighty four kilograms of weight.", "ex_pr": "Эйти фор килограмз оф уэйт.", "ex_ky": "Сексен төрт килограмм салмак."},
    {"en": "Eighty five", "pr": "эйти файв", "ky": "Сексен беш", "ex": "Eighty five degrees Fahrenheit.", "ex_pr": "Эйти файв дигриз фарэнхайт.", "ex_ky": "Сексен беш градус Фаренгейт."},
    {"en": "Eighty six", "pr": "эйти сикс", "ky": "Сексен алты", "ex": "Eighty six the item (remove).", "ex_pr": "Эйти сикс зэ айтэм (римув).", "ex_ky": "Затты сексен алты (алып сал)."},
    {"en": "Eighty seven", "pr": "эйти сэвэн", "ky": "Сексен жети", "ex": "Eighty seven million people.", "ex_pr": "Эйти сэвэн миллион пипл.", "ex_ky": "Сексен жети миллион адам."},
    {"en": "Eighty eight", "pr": "эйти эйт", "ky": "Сексен сегиз", "ex": "Eighty eight keys on piano.", "ex_pr": "Эйти эйт кис он пиано.", "ex_ky": "Пианинодо сексен сегиз клавиша."},
    {"en": "Eighty nine", "pr": "эйти найн", "ky": "Сексен тогуз", "ex": "Eighty nine cents per pound.", "ex_pr": "Эйти найн сэнтс пэр паунд.", "ex_ky": "Фунтуна сексен тогуз цент."},
    {"en": "Ninety", "pr": "найти", "ky": "Токсон", "ex": "Ninety nine percent of problems.", "ex_pr": "Найти найн пэсэнт ов проблэмз.", "ex_ky": "Көйгөйлөрдүн токсон тогуз проценти."},
    {"en": "Ninety one", "pr": "найти уан", "ky": "Токсон бир", "ex": "Ninety one percent of water.", "ex_pr": "Найти уан пэсэнт ов уотэр.", "ex_ky": "Суунун токсон бир проценти."},
    {"en": "Ninety two", "pr": "найти ту", "ky": "Токсон эки", "ex": "Ninety two percent of people.", "ex_pr": "Найти ту пэсэнт ов пипл.", "ex_ky": "Адамдардын токсон эки проценти."},
    {"en": "Ninety three", "pr": "найти сри", "ky": "Токсон үч", "ex": "Ninety three percent of happiness.", "ex_pr": "Найти сри пэсэнт ов хэппинэс.", "ex_ky": "Бакыттын токсон үч проценти."},
    {"en": "Ninety four", "pr": "найти фор", "ky": "Токсон төрт", "ex": "Ninety four percent of success.", "ex_pr": "Найти фор пэсэнт ов саксес.", "ex_ky": "Ийгиликтин токсон төрт проценти."},
    {"en": "Ninety five", "pr": "найти файв", "ky": "Токсон беш", "ex": "Ninety five percent of doctors agree.", "ex_pr": "Найти файв пэсэнт ов докторз эгри.", "ex_ky": "Дарыгерлердин токсон беш проценти макул."},
    {"en": "Ninety six", "pr": "найти сикс", "ky": "Токсон алты", "ex": "Ninety six percent of customers.", "ex_pr": "Найти сикс пэсэнт ов кастомерз.", "ex_ky": "Кардарлардын токсон алты проценти."},
    {"en": "Ninety seven", "pr": "найти сэвэн", "ky": "Токсон жети", "ex": "Ninety seven percent of faith.", "ex_pr": "Найти сэвэн пэсэнт ов фэйс.", "ex_ky": "Ишенимдин токсон жети проценти."},
    {"en": "Ninety eight", "pr": "найти эйт", "ky": "Токсон сегиз", "ex": "Ninety eight percent of plan.", "ex_pr": "Найти эйт пэсэнт ов плэн.", "ex_ky": "Пландын токсон сегиз проценти."},
    {"en": "Ninety nine", "pr": "найти найн", "ky": "Токсон тогуз", "ex": "Ninety nine red balloons.", "ex_pr": "Найти найн рэд бэлунз.", "ex_ky": "Токсон тогуз кызыл шар."},
    {"en": "One hundred", "pr": "уан хандрэд", "ky": "Жүз", "ex": "One hundred percent guarantee.", "ex_pr": "Уан хандрэд пэсэнт гэранти.", "ex_ky": "Жүз процент кепилдик."},
    {"en": "One hundred one", "pr": "уан хандрэд уан", "ky": "Жүз бир", "ex": "One hundred one dalmatians.", "ex_pr": "Уан хандрэд уан дэлмэйшнз.", "ex_ky": "Жүз бир далматин."},
    {"en": "One hundred two", "pr": "уан хандрэд ту", "ky": "Жүз эки", "ex": "One hundred two years old.", "ex_pr": "Уан хандрэд ту йирз олд.", "ex_ky": "Жүз эки жашта."},
    {"en": "One hundred three", "pr": "уан хандрэд сри", "ky": "Жүз үч", "ex": "One hundred three kilometers.", "ex_pr": "Уан хандрэд сри киломитэрз.", "ex_ky": "Жүз үч километр."},
    {"en": "One hundred four", "pr": "уан хандрэд фор", "ky": "Жүз төрт", "ex": "One hundred four floors building.", "ex_pr": "Уан хандрэд фор флорз билдинг.", "ex_ky": "Жүз төрт кабаттуу имарат."},
    {"en": "One hundred five", "pr": "уан хандрэд файв", "ky": "Жүз беш", "ex": "One hundred five degrees.", "ex_pr": "Уан хандрэд файв дигриз.", "ex_ky": "Жүз беш градус."},
    {"en": "One hundred six", "pr": "уан хандрэд сикс", "ky": "Жүз алты", "ex": "One hundred six dollars.", "ex_pr": "Уан хандрэд сикс долларз.", "ex_ky": "Жүз алты доллар."},
    {"en": "One hundred seven", "pr": "уан хандрэд сэвэн", "ky": "Жүз жети", "ex": "One hundred seven days.", "ex_pr": "Уан хандрэд сэвэн дэйз.", "ex_ky": "Жүз жети күн."},
    {"en": "One hundred eight", "pr": "уан хандрэд эйт", "ky": "Жүз сегиз", "ex": "One hundred eight hours.", "ex_pr": "Уан хандрэд эйт ауэрз.", "ex_ky": "Жүз сегиз саат."},
    {"en": "One hundred nine", "pr": "уан хандрэд найн", "ky": "Жүз тогуз", "ex": "One hundred nine percent effort.", "ex_pr": "Уан хандрэд найн пэсэнт эффорт.", "ex_ky": "Жүз тогуз процент аракет."},
    {"en": "One hundred ten", "pr": "уан хандрэд тэн", "ky": "Жүз он", "ex": "One hundred ten kilograms.", "ex_pr": "Уан хандрэд тэн килограмз.", "ex_ky": "Жүз он килограмм."},
    {"en": "One hundred twenty", "pr": "уан хандрэд туэнти", "ky": "Жүз жыйырма", "ex": "One hundred twenty minutes.", "ex_pr": "Уан хандрэд туэнти минут.", "ex_ky": "Жүз жыйырма мүнөт."},
    {"en": "One hundred thirty", "pr": "уан хандрэд сёрти", "ky": "Жүз отуз", "ex": "One hundred thirty dollars.", "ex_pr": "Уан хандрэд сёрти долларз.", "ex_ky": "Жүз отуз доллар."},
    {"en": "One hundred forty", "pr": "уан хандрэд фоти", "ky": "Жүз кырк", "ex": "One hundred forty characters.", "ex_pr": "Уан хандрэд фоти кэрэктэрз.", "ex_ky": "Жүз кырк символ."},
    {"en": "One hundred fifty", "pr": "уан хандрэд фифти", "ky": "Жүз элүү", "ex": "One hundred fifty pounds.", "ex_pr": "Уан хандрэд фифти паундз.", "ex_ky": "Жүз элүү фунт."},
    {"en": "One hundred sixty", "pr": "уан хандрэд сиксти", "ky": "Жүз алтымыш", "ex": "One hundred sixty centimeters.", "ex_pr": "Уан хандрэд сиксти сэнтимитэрз.", "ex_ky": "Жүз алтымыш сантиметр."},
    {"en": "One hundred seventy", "pr": "уан хандрэд сэвэнти", "ky": "Жүз жетимиш", "ex": "One hundred seventy beats per minute.", "ex_pr": "Уан хандрэд сэвэнти битс пэр минут.", "ex_ky": "Мүнөтүнө жүз жетимиш сокку."},
    {"en": "One hundred eighty", "pr": "уан хандрэд эйти", "ky": "Жүз сексен", "ex": "One hundred eighty degrees turn.", "ex_pr": "Уан хандрэд эйти дигриз тёрн.", "ex_ky": "Жүз сексен градуска бурулуу."},
    {"en": "One hundred ninety", "pr": "уан хандрэд найти", "ky": "Жүз токсон", "ex": "One hundred ninety dollars.", "ex_pr": "Уан хандрэд найти долларз.", "ex_ky": "Жүз токсон доллар."},
    {"en": "Two hundred", "pr": "ту хандрэд", "ky": "Эки жүз", "ex": "Two hundred dollars.", "ex_pr": "Ту хандрэд долларз.", "ex_ky": "Эки жүз доллар."},
    {"en": "Three hundred", "pr": "сри хандрэд", "ky": "Үч жүз", "ex": "Three hundred Spartans.", "ex_pr": "Сри хандрэд спартанз.", "ex_ky": "Үч жүз спартандык."},
    {"en": "Four hundred", "pr": "фор хандрэд", "ky": "Төрт жүз", "ex": "Four hundred meters race.", "ex_pr": "Фор хандрэд митэрз рэйс.", "ex_ky": "Төрт жүз метрге жарыш."},
    {"en": "Five hundred", "pr": "файв хандрэд", "ky": "Беш жүз", "ex": "Five hundred miles song.", "ex_pr": "Файв хандрэд майлз сонг.", "ex_ky": "Беш жүз миль ыры."}
];
