const words = [
    {"en": "Hello", "pr": "хэлоу", "ky": "Салам", "ex": "Hello, how are you?", "ex_pr": "Хэлоу, хау ар ю?", "ex_ky": "Салам, кандайсың?"},
    {"en": "Goodbye", "pr": "гудбай", "ky": "Кош болуңуз", "ex": "Goodbye, see you later.", "ex_pr": "Гудбай, си ю лэйтэр.", "ex_ky": "Кош болуңуз, кийин көрүшкөнчө."},
    {"en": "Thank you", "pr": "сэнк ю", "ky": "Рахмат", "ex": "Thank you for your help.", "ex_pr": "Сэнк ю фор ёр хэлп.", "ex_ky": "Жардамыңыз үчүн рахмат."},
    {"en": "Please", "pr": "плиз", "ky": "Өтүнөмүн", "ex": "Please help me.", "ex_pr": "Плиз хэлп ми.", "ex_ky": "Мага жардам бериңизчи."},
    {"en": "Sorry", "pr": "сорри", "ky": "Кечириңиз", "ex": "I am sorry.", "ex_pr": "Ай эм сорри.", "ex_ky": "Мен кечирим сурайм."},
    {"en": "Yes", "pr": "ес", "ky": "Ооба", "ex": "Yes, I understand.", "ex_pr": "Ес, ай андерстэнд.", "ex_ky": "Ооба, мен түшүндүм."},
    {"en": "No", "pr": "ноу", "ky": "Жок", "ex": "No, thank you.", "ex_pr": "Ноу, сэнк ю.", "ex_ky": "Жок, рахмат."},
    {"en": "Good", "pr": "гуд", "ky": "Жакшы", "ex": "This is good.", "ex_pr": "Зис из гуд.", "ex_ky": "Бул жакшы."},
    {"en": "Bad", "pr": "бэд", "ky": "Жаман", "ex": "That is bad.", "ex_pr": "Дэт из бэд.", "ex_ky": "Ал жаман."},
    {"en": "Big", "pr": "биг", "ky": "Чоң", "ex": "This is big.", "ex_pr": "Зис из биг.", "ex_ky": "Бул чоң."},
    {"en": "Small", "pr": "смол", "ky": "Кичине", "ex": "That is small.", "ex_pr": "Дэт из смол.", "ex_ky": "Ал кичине."},
    {"en": "Happy", "pr": "хэппи", "ky": "Бактылуу", "ex": "I am happy.", "ex_pr": "Ай эм хэппи.", "ex_ky": "Мен бактылуумун."},
    {"en": "Sad", "pr": "сэд", "ky": "Капа", "ex": "She is sad.", "ex_pr": "Ши из сэд.", "ex_ky": "Ал капа."},
    {"en": "Beautiful", "pr": "бьютифул", "ky": "Кооз", "ex": "You are beautiful.", "ex_pr": "Ю а бьютифул.", "ex_ky": "Сен коозсуң."},
    {"en": "Ugly", "pr": "агли", "ky": "Коркунучтуу", "ex": "It is ugly.", "ex_pr": "Ит из агли.", "ex_ky": "Ал коркунучтуу."},
    {"en": "New", "pr": "нью", "ky": "Жаңы", "ex": "This is new.", "ex_pr": "Зис из нью.", "ex_ky": "Бул жаңы."},
    {"en": "Old", "pr": "олд", "ky": "Эски", "ex": "This is old.", "ex_pr": "Зис из олд.", "ex_ky": "Бул эски."},
    {"en": "Hot", "pr": "хот", "ky": "Ысык", "ex": "The soup is hot.", "ex_pr": "Зэ суп из хот.", "ex_ky": "Шорпо ысык."},
    {"en": "Cold", "pr": "колд", "ky": "Муздак", "ex": "The water is cold.", "ex_pr": "Зэ уотэр из колд.", "ex_ky": "Суу муздак."},
    {"en": "Eat", "pr": "ит", "ky": "Же", "ex": "I eat breakfast.", "ex_pr": "Ай ит брэкфэст.", "ex_ky": "Мен таңкы ашты жейм."},
    {"en": "Drink", "pr": "дринк", "ky": "Ич", "ex": "I drink water.", "ex_pr": "Ай дринк уотэр.", "ex_ky": "Мен суу ичем."},
    {"en": "Sleep", "pr": "слип", "ky": "Укта", "ex": "I sleep well.", "ex_pr": "Ай слип вэл.", "ex_ky": "Мен жакшы уктайм."},
    {"en": "Work", "pr": "уорк", "ky": "Иште", "ex": "I work every day.", "ex_pr": "Ай уорк эври дэй.", "ex_ky": "Мен күн сайын иштейм."},
    {"en": "Study", "pr": "стади", "ky": "Оку", "ex": "I study English.", "ex_pr": "Ай стади инглиш.", "ex_ky": "Мен англис тилин окуйм."},
    {"en": "Read", "pr": "рид", "ky": "Оку", "ex": "I read books.", "ex_pr": "Ай рид букс.", "ex_ky": "Мен китептерди окуйм."},
    {"en": "Write", "pr": "райт", "ky": "Жаз", "ex": "I write a letter.", "ex_pr": "Ай райт э леттэр.", "ex_ky": "Мен кат жазам."},
    {"en": "Speak", "pr": "спик", "ky": "Сүйлө", "ex": "I speak Kyrgyz.", "ex_pr": "Ай спик кыргыз.", "ex_ky": "Мен кыргызча сүйлөйм."},
    {"en": "Listen", "pr": "лисн", "ky": "Ук", "ex": "Listen to music.", "ex_pr": "Лисн ту мьюзик.", "ex_ky": "Музыка ук."},
    {"en": "Watch", "pr": "уотч", "ky": "Көр", "ex": "I watch TV.", "ex_pr": "Ай уотч тиви.", "ex_ky": "Мен телевизор көрөм."},
    {"en": "Go", "pr": "гоу", "ky": "Бар", "ex": "I go to school.", "ex_pr": "Ай гоу ту скул.", "ex_ky": "Мен мектепке барам."},
    {"en": "Come", "pr": "кам", "ky": "Кел", "ex": "Come here.", "ex_pr": "Кам хиэр.", "ex_ky": "Бул жакка кел."},
    {"en": "Sit", "pr": "сит", "ky": "Олтур", "ex": "Please sit down.", "ex_pr": "Плиз сит даун.", "ex_ky": "Сураныч, олтуруңуз."},
    {"en": "Stand", "pr": "стэнд", "ky": "Тур", "ex": "Stand up.", "ex_pr": "Стэнд ап.", "ex_ky": "Тургула."},
    {"en": "Run", "pr": "ран", "ky": "Чурка", "ex": "I run fast.", "ex_pr": "Ай ран фаст.", "ex_ky": "Мен тез чуркайм."},
    {"en": "Walk", "pr": "уок", "ky": "Бас", "ex": "I walk slowly.", "ex_pr": "Ай уок слоули.", "ex_ky": "Мен жай басам."},
    {"en": "Buy", "pr": "бай", "ky": "Сат", "ex": "I buy food.", "ex_pr": "Ай бай фуд.", "ex_ky": "Мен тамак сатып алам."},
    {"en": "Sell", "pr": "сэл", "ky": "Сат", "ex": "They sell cars.", "ex_pr": "Дэй сэл карз.", "ex_ky": "Алар машина сатышат."},
    {"en": "Open", "pr": "оупэн", "ky": "Ач", "ex": "Open the door.", "ex_pr": "Оупэн зэ дор.", "ex_ky": "Эшикти ач."},
    {"en": "Close", "pr": "клоуз", "ky": "Жап", "ex": "Close the window.", "ex_pr": "Клоуз зэ уиндоу.", "ex_ky": "Терезени жап."},
    {"en": "Start", "pr": "старт", "ky": "Башта", "ex": "Start the lesson.", "ex_pr": "Старт зэ лесн.", "ex_ky": "Сабакты башта."},
    {"en": "Finish", "pr": "финиш", "ky": "Бүт", "ex": "Finish your homework.", "ex_pr": "Финиш ёр хоум уорк.", "ex_ky": "Үй тапшырмаңды бүтүр."},
    {"en": "Help", "pr": "хэлп", "ky": "Жардам", "ex": "Can you help me?", "ex_pr": "Кэн ю хэлп ми?", "ex_ky": "Мага жардам бере аласыңбы?"},
    {"en": "Ask", "pr": "аск", "ky": "Сура", "ex": "I ask a question.", "ex_pr": "Ай аск э куэсчн.", "ex_ky": "Мен суроо берем."},
    {"en": "Answer", "pr": "ансэр", "ky": "Жооп бер", "ex": "Answer the question.", "ex_pr": "Ансэр зэ куэсчн.", "ex_ky": "Суроого жооп бер."},
    {"en": "Give", "pr": "гив", "ky": "Бер", "ex": "Give me water.", "ex_pr": "Гив ми уотэр.", "ex_ky": "Мага суу бер."},
    {"en": "Take", "pr": "тэйк", "ky": "Ал", "ex": "Take this.", "ex_pr": "Тэйк зис.", "ex_ky": "Муну ал."},
    {"en": "Live", "pr": "лив", "ky": "Жаша", "ex": "I live in Bishkek.", "ex_pr": "Ай лив ин Бишкек.", "ex_ky": "Мен Бишкекте жашайм."},
    {"en": "Love", "pr": "лав", "ky": "Сүй", "ex": "I love you.", "ex_pr": "Ай лав ю.", "ex_ky": "Мен сени сүйөм."},
    {"en": "Like", "pr": "лайк", "ky": "Жактыр", "ex": "I like coffee.", "ex_pr": "Ай лайк кофи.", "ex_ky": "Мен кофени жактырам."},
    {"en": "Hate", "pr": "хейт", "ky": "Жек көр", "ex": "I hate lies.", "ex_pr": "Ай хейт лайз.", "ex_ky": "Мен калпты жек көрөм."},
    {"en": "Want", "pr": "уонт", "ky": "Каала", "ex": "I want water.", "ex_pr": "Ай уонт уотэр.", "ex_ky": "Мен суу каалайм."},
    {"en": "Need", "pr": "нид", "ky": "Керек", "ex": "I need help.", "ex_pr": "Ай нид хэлп.", "ex_ky": "Мага жардам керек."},
    {"en": "Have", "pr": "хэв", "ky": "Бар", "ex": "I have a car.", "ex_pr": "Ай хэв э кар.", "ex_ky": "Менин машинам бар."},
    {"en": "Get", "pr": "гет", "ky": "Ал", "ex": "I get a job.", "ex_pr": "Ай гет э джоб.", "ex_ky": "Мен жумуш алам."},
    {"en": "Make", "pr": "мэйк", "ky": "Жаса", "ex": "I make tea.", "ex_pr": "Ай мэйк ти.", "ex_ky": "Мен чай жасайм."},
    {"en": "Do", "pr": "ду", "ky": "Кыл", "ex": "I do my work.", "ex_pr": "Ай ду май уорк.", "ex_ky": "Мен ишимди кылам."},
    {"en": "Say", "pr": "сей", "ky": "Айт", "ex": "I say hello.", "ex_pr": "Ай сей хэлоу.", "ex_ky": "Мен салам айтам."},
    {"en": "Tell", "pr": "тэл", "ky": "Айт", "ex": "Tell me a story.", "ex_pr": "Тэл ми э стори.", "ex_ky": "Мага аңгеме айт."},
    {"en": "Think", "pr": "синк", "ky": "Ойло", "ex": "I think so.", "ex_pr": "Ай синк соу.", "ex_ky": "Мен ошондой ойлойм."},
    {"en": "Know", "pr": "ноу", "ky": "Бил", "ex": "I know you.", "ex_pr": "Ай ноу ю.", "ex_ky": "Мен сени билем."},
    {"en": "Understand", "pr": "андерстэнд", "ky": "Түшүн", "ex": "I understand you.", "ex_pr": "Ай андерстэнд ю.", "ex_ky": "Мен сени түшүндүм."},
    {"en": "Remember", "pr": "римэмбэр", "ky": "Эсте", "ex": "I remember that.", "ex_pr": "Ай римэмбэр дэт.", "ex_ky": "Мен муну эстейм."},
    {"en": "Forget", "pr": "форгет", "ky": "Унут", "ex": "I forget your name.", "ex_pr": "Ай форгет ёр нэйм.", "ex_ky": "Мен сенин атыңды унуттум."},
    {"en": "Learn", "pr": "лёрн", "ky": "Үйрөн", "ex": "I learn Kyrgyz.", "ex_pr": "Ай лёрн кыргыз.", "ex_ky": "Мен кыргыз тилин үйрөнөм."},
    {"en": "Teach", "pr": "тич", "ky": "Үйрөт", "ex": "I teach English.", "ex_pr": "Ай тич инглиш.", "ex_ky": "Мен англис тилин үйрөтөм."},
    {"en": "Find", "pr": "файнд", "ky": "Тап", "ex": "I find my phone.", "ex_pr": "Ай файнд май фоун.", "ex_ky": "Мен телефонумду таптым."},
    {"en": "Lose", "pr": "луз", "ky": "Жогот", "ex": "I lose my keys.", "ex_pr": "Ай луз май кис.", "ex_ky": "Мен ачкычымды жоготтум."},
    {"en": "Keep", "pr": "кип", "ky": "Сакта", "ex": "Keep this secret.", "ex_pr": "Кип зис сикрит.", "ex_ky": "Муну сыр сакта."},
    {"en": "Wait", "pr": "уэйт", "ky": "Күт", "ex": "Wait for me.", "ex_pr": "Уэйт фор ми.", "ex_ky": "Мени күт."},
    {"en": "Call", "pr": "кол", "ky": "Чакыр", "ex": "Call me later.", "ex_pr": "Кол ми лэйтэр.", "ex_ky": "Мага кийин чал."},
    {"en": "Meet", "pr": "мит", "ky": "Жолук", "ex": "Meet my friend.", "ex_pr": "Мит май фрэнд.", "ex_ky": "Менин досум менен тааныш."},
    {"en": "Leave", "pr": "лив", "ky": "Кет", "ex": "Leave the room.", "ex_pr": "Лив зэ рум.", "ex_ky": "Бөлмөдөн чык."},
    {"en": "Stay", "pr": "стэй", "ky": "Кал", "ex": "Stay here.", "ex_pr": "Стэй хиэр.", "ex_ky": "Бул жакта кал."},
    {"en": "Change", "pr": "чейнж", "ky": "Өзгөрт", "ex": "Change your clothes.", "ex_pr": "Чейнж ёр клоуз.", "ex_ky": "Кийимиңди алмаштыр."},
    {"en": "Try", "pr": "трай", "ky": "Аракет кыл", "ex": "Try again.", "ex_pr": "Трай эгейн.", "ex_ky": "Кайра аракет кыл."},
    {"en": "Use", "pr": "юз", "ky": "Колдон", "ex": "Use your phone.", "ex_pr": "Юз ёр фоун.", "ex_ky": "Телефонуңду колдон."},
    {"en": "Play", "pr": "плэй", "ky": "Ойно", "ex": "Play football.", "ex_pr": "Плэй футбол.", "ex_ky": "Футбол ойно."},
    {"en": "Cook", "pr": "кук", "ky": "Бышыр", "ex": "I cook dinner.", "ex_pr": "Ай кук динэр.", "ex_ky": "Мен кечки тамак бышырам."},
    {"en": "Clean", "pr": "клин", "ky": "Тазала", "ex": "Clean the room.", "ex_pr": "Клин зэ рум.", "ex_ky": "Бөлмөнү тазала."},
    {"en": "Wash", "pr": "уош", "ky": "Жуу", "ex": "Wash your hands.", "ex_pr": "Уош ёр хэндз.", "ex_ky": "Колуңду жуу."},
    {"en": "Drive", "pr": "драйв", "ky": "Айда", "ex": "Drive carefully.", "ex_pr": "Драйв кэафули.", "ex_ky": "Абайлап айда."},
    {"en": "Fly", "pr": "флай", "ky": "Уч", "ex": "Birds fly.", "ex_pr": "Бёрдс флай.", "ex_ky": "Куштар учат."},
    {"en": "Swim", "pr": "суим", "ky": "Сүз", "ex": "I swim well.", "ex_pr": "Ай суим вэл.", "ex_ky": "Мен жакшы сүзөм."},
    {"en": "Jump", "pr": "джамп", "ky": "Секір", "ex": "Jump high.", "ex_pr": "Джамп хай.", "ex_ky": "Бийикке секир."},
    {"en": "Dance", "pr": "дэнс", "ky": "Бий", "ex": "Dance with me.", "ex_pr": "Дэнс уиз ми.", "ex_ky": "Мени менен бийле."},
    {"en": "Sing", "pr": "синг", "ky": "Ырда", "ex": "Sing a song.", "ex_pr": "Синг э сонг.", "ex_ky": "Ыр ырда."},
    {"en": "Laugh", "pr": "лаф", "ky": "Күл", "ex": "Laugh loudly.", "ex_pr": "Лаф лаудли.", "ex_ky": "Катуу күл."},
    {"en": "Cry", "pr": "край", "ky": "Ыйла", "ex": "Don't cry.", "ex_pr": "Донт край.", "ex_ky": "Ыйлаба."},
    {"en": "Smile", "pr": "смайл", "ky": "Жылмай", "ex": "Smile please.", "ex_pr": "Смайл плиз.", "ex_ky": "Сураныч жылмай."},
    {"en": "Rest", "pr": "рэст", "ky": "Эс ал", "ex": "Rest a little.", "ex_pr": "Рэст э литл.", "ex_ky": "Бирам эс ал."},
    {"en": "Travel", "pr": "трэвэл", "ky": "Саякатта", "ex": "I travel a lot.", "ex_pr": "Ай трэвэл э лот.", "ex_ky": "Мен көп саякаттайм."},
    {"en": "Visit", "pr": "визит", "ky": "Зыярат кыл", "ex": "Visit your parents.", "ex_pr": "Визит ёр пээрэнтс.", "ex_ky": "Ата-энеңе бар."},
    {"en": "Invite", "pr": "инвайт", "ky": "Чакыр", "ex": "Invite your friend.", "ex_pr": "Инвайт ёр фрэнд.", "ex_ky": "Досуңду чакыр."},
    {"en": "Show", "pr": "шоу", "ky": "Көрсөт", "ex": "Show me your photo.", "ex_pr": "Шоу ми ёр фотоу.", "ex_ky": "Мага сүрөтүңдү көрсөт."},
    {"en": "Send", "pr": "сэнд", "ky": "Жөнөт", "ex": "Send a message.", "ex_pr": "Сэнд э мэссиж.", "ex_ky": "Билдирме жөнөт."},
    {"en": "Receive", "pr": "рисив", "ky": "Ал", "ex": "I receive a gift.", "ex_pr": "Ай рисив э гифт.", "ex_ky": "Мен белек алдым."},
    {"en": "Keep", "pr": "кип", "ky": "Сакта", "ex": "Keep it safe.", "ex_pr": "Кип ит сейф.", "ex_ky": "Аны коопсуз сакта."},
    {"en": "Break", "pr": "брэйк", "ky": "Сындыр", "ex": "Don't break it.", "ex_pr": "Донт брэйк ит.", "ex_ky": "Аны сындырба."},
    {"en": "Fix", "pr": "фикс", "ky": "Оңдо", "ex": "Fix the car.", "ex_pr": "Фикс зэ кар.", "ex_ky": "Машинаны оңдо."},
    {"en": "Build", "pr": "билд", "ky": "Кур", "ex": "Build a house.", "ex_pr": "Билд э хаус.", "ex_ky": "Үй кур."},
    {"en": "Grow", "pr": "гроу", "ky": "Өстүр", "ex": "Grow flowers.", "ex_pr": "Гроу флауэрс.", "ex_ky": "Гүл өстүр."},
    {"en": "Cut", "pr": "кат", "ky": "Кес", "ex": "Cut the bread.", "ex_pr": "Кат зэ брэд.", "ex_ky": "Нан кес."},
    {"en": "Push", "pr": "пуш", "ky": "Түрт", "ex": "Push the door.", "ex_pr": "Пуш зэ дор.", "ex_ky": "Эшикти түрт."},
    {"en": "Pull", "pr": "пул", "ky": "Тарт", "ex": "Pull the rope.", "ex_pr": "Пул зэ роуп.", "ex_ky": "Арканды тарт."},
    {"en": "Lift", "pr": "лифт", "ky": "Көтөр", "ex": "Lift the box.", "ex_pr": "Лифт зэ бокс.", "ex_ky": "Кутуну көтөр."},
    {"en": "Carry", "pr": "кэри", "ky": "Ташы", "ex": "Carry the bag.", "ex_pr": "Кэри зэ бэг.", "ex_ky": "Багжды ташы."},
    {"en": "Hold", "pr": "холд", "ky": "Карма", "ex": "Hold my hand.", "ex_pr": "Холд май хэнд.", "ex_ky": "Менин колумду карма."},
    {"en": "Drop", "pr": "дроп", "ky": "Түшүр", "ex": "Don't drop it.", "ex_pr": "Донт дроп ит.", "ex_ky": "Аны түшүрбө."},
    {"en": "Catch", "pr": "кэтч", "ky": "Карма", "ex": "Catch the ball.", "ex_pr": "Кэтч зэ бол.", "ex_ky": "Допту карма."},
    {"en": "Throw", "pr": "сроу", "ky": "Ыргыт", "ex": "Throw the ball.", "ex_pr": "Сроу зэ бол.", "ex_ky": "Допту ыргыт."},
    {"en": "Kick", "pr": "кик", "ky": "Теп", "ex": "Kick the ball.", "ex_pr": "Кик зэ бол.", "ex_ky": "Допту теп."},
    {"en": "Hit", "pr": "хит", "ky": "Ур", "ex": "Don't hit me.", "ex_pr": "Донт хит ми.", "ex_ky": "Мени урба."},
    {"en": "Touch", "pr": "тач", "ky": "Тий", "ex": "Don't touch.", "ex_pr": "Донт тач.", "ex_ky": "Тийбе."},
    {"en": "Feel", "pr": "фил", "ky": "Сез", "ex": "I feel good.", "ex_pr": "Ай фил гуд.", "ex_ky": "Мен өзүмдү жакшы сезем."},
    {"en": "Hear", "pr": "хиэр", "ky": "Ук", "ex": "I hear you.", "ex_pr": "Ай хиэр ю.", "ex_ky": "Мен сени уктум."},
    {"en": "See", "pr": "си", "ky": "Көр", "ex": "I see you.", "ex_pr": "Ай си ю.", "ex_ky": "Мен сени көрдүм."},
    {"en": "Look", "pr": "лук", "ky": "Кара", "ex": "Look at me.", "ex_pr": "Лук эт ми.", "ex_ky": "Мага кара."},
    {"en": "Smell", "pr": "смэл", "ky": "Жытта", "ex": "Smell the flower.", "ex_pr": "Смэл зэ флауэр.", "ex_ky": "Гүлдү жытта."},
    {"en": "Taste", "pr": "тэйст", "ky": "Даам", "ex": "Taste the soup.", "ex_pr": "Тэйст зэ суп.", "ex_ky": "Шорпонун даамын тат."},
    {"en": "Kiss", "pr": "кис", "ky": "Өп", "ex": "Kiss your mom.", "ex_pr": "Кис ёр мом.", "ex_ky": "Апаңды өп."},
    {"en": "Hug", "pr": "хаг", "ky": "Куч", "ex": "Hug your friend.", "ex_pr": "Хаг ёр фрэнд.", "ex_ky": "Досуңду куч."},
    {"en": "Fight", "pr": "файт", "ky": "Согуш", "ex": "Don't fight.", "ex_pr": "Донт файт.", "ex_ky": "Согушпа."},
    {"en": "Win", "pr": "уин", "ky": "Жең", "ex": "We will win.", "ex_pr": "Уи уил уин.", "ex_ky": "Биз жеңебиз."},
    {"en": "Lose", "pr": "луз", "ky": "Утул", "ex": "I don't want to lose.", "ex_pr": "Ай донт уонт ту луз.", "ex_ky": "Мен утулгым келбейт."},
    {"en": "Save", "pr": "сейв", "ky": "Куткар", "ex": "Save money.", "ex_pr": "Сейв мани.", "ex_ky": "Акча үнөмдө."},
    {"en": "Spend", "pr": "спэнд", "ky": "Сарыпта", "ex": "Spend time.", "ex_pr": "Спэнд тайм.", "ex_ky": "Убакыт өткөр."},
    {"en": "Pay", "pr": "пэй", "ky": "Төлө", "ex": "Pay the bill.", "ex_pr": "Пэй зэ бил.", "ex_ky": "Эсеп төлө."},
    {"en": "Cost", "pr": "кост", "ky": "Турат", "ex": "How much does it cost?", "ex_pr": "Хау мач даз ит кост?", "ex_ky": "Ал канча турат?"},
    {"en": "Sell", "pr": "сэл", "ky": "Сат", "ex": "Sell your car.", "ex_pr": "Сэл ёр кар.", "ex_ky": "Машинаңды сат."},
    {"en": "Buy", "pr": "бай", "ky": "Сат", "ex": "Buy milk.", "ex_pr": "Бай милк.", "ex_ky": "Сүт сатып ал."},
    {"en": "Borrow", "pr": "борроу", "ky": "Карыз ал", "ex": "Can I borrow your pen?", "ex_pr": "Кэн ай борроу ёр пэн?", "ex_ky": "Сиздин калемиңизди ала тұрайынбы?"},
    {"en": "Lend", "pr": "лэнд", "ky": "Карыз бер", "ex": "Lend me money.", "ex_pr": "Лэнд ми мани.", "ex_ky": "Мага акча бер."},
    {"en": "Keep", "pr": "кип", "ky": "Сакта", "ex": "Keep the change.", "ex_pr": "Кип зэ чейнж.", "ex_ky": "Кайчыны сакта."},
    {"en": "Wear", "pr": "уэар", "ky": "Кий", "ex": "Wear a coat.", "ex_pr": "Уэар э коут.", "ex_ky": "Пальто кий."},
    {"en": "Take off", "pr": "тэйк оф", "ky": "Чеч", "ex": "Take off your shoes.", "ex_pr": "Тэйк оф ёр шуз.", "ex_ky": "Бут кийимиңди чеч."},
    {"en": "Put on", "pr": "пут он", "ky": "Кий", "ex": "Put on your hat.", "ex_pr": "Пут он ёр хэт.", "ex_ky": "Баш кийимиңди кий."},
    {"en": "Dress", "pr": "дрес", "ky": "Кийн", "ex": "Dress warmly.", "ex_pr": "Дрес уормли.", "ex_ky": "Жылуу кийн."},
    {"en": "Undress", "pr": "анрес", "ky": "Чечин", "ex": "Undress before sleep.", "ex_pr": "Анрес бифор слип.", "ex_ky": "Уктаар алдында чечин."},
    {"en": "Sleep", "pr": "слип", "ky": "Укта", "ex": "Sleep early.", "ex_pr": "Слип эрли.", "ex_ky": "Эрте укта."},
    {"en": "Wake up", "pr": "уэйк ап", "ky": "Ойгон", "ex": "Wake up early.", "ex_pr": "Уэйк ап эрли.", "ex_ky": "Эрте ойгон."},
    {"en": "Dream", "pr": "дрим", "ky": "Кыялдан", "ex": "I have a dream.", "ex_pr": "Ай хэв э дрим.", "ex_ky": "Менин кыялым бар."},
    {"en": "Wish", "pr": "уиш", "ky": "Тиле", "ex": "Make a wish.", "ex_pr": "Мэйк э уиш.", "ex_ky": "Тилек кыл."},
    {"en": "Hope", "pr": "хоуп", "ky": "Үмүт кыл", "ex": "I hope so.", "ex_pr": "Ай хоуп соу.", "ex_ky": "Мен ага үмүттөнөм."},
    {"en": "Believe", "pr": "билиф", "ky": "Ишен", "ex": "I believe you.", "ex_pr": "Ай билиф ю.", "ex_ky": "Мен сага ишенем."},
    {"en": "Trust", "pr": "траст", "ky": "Ишен", "ex": "Trust me.", "ex_pr": "Траст ми.", "ex_ky": "Мага ишен."},
    {"en": "Respect", "pr": "риспект", "ky": "Сыйла", "ex": "Respect your elders.", "ex_pr": "Риспект ёр элдэрс.", "ex_ky": "Улууларды сыйла."},
    {"en": "Forgive", "pr": "форгив", "ky": "Кечир", "ex": "Forgive me.", "ex_pr": "Форгив ми.", "ex_ky": "Мени кечир."},
    {"en": "Promise", "pr": "промист", "ky": "Убада кыл", "ex": "Promise me.", "ex_pr": "Промист ми.", "ex_ky": "Мага убада бер."},
    {"en": "Swear", "pr": "суэар", "ky": "Ант кыл", "ex": "I swear.", "ex_pr": "Ай суэар.", "ex_ky": "Мен ант берем."},
    {"en": "Agree", "pr": "агри", "ky": "Макул", "ex": "I agree with you.", "ex_pr": "Ай агри уиз ю.", "ex_ky": "Мен сага макулмун."},
    {"en": "Disagree", "pr": "дисагри", "ky": "Макул эмес", "ex": "I disagree.", "ex_pr": "Ай дисагри.", "ex_ky": "Мен макул эмесмин."},
    {"en": "Argue", "pr": "аргью", "ky": "Тал", "ex": "Don't argue.", "ex_pr": "Донт аргью.", "ex_ky": "Талашпа."},
    {"en": "Explain", "pr": "иксплейн", "ky": "Түшүндүр", "ex": "Explain please.", "ex_pr": "Иксплейн плиз.", "ex_ky": "Сураныч түшүндүр."},
    {"en": "Describe", "pr": "дискрайб", "ky": "Сүрөттө", "ex": "Describe him.", "ex_pr": "Дискрайб хим.", "ex_ky": "Аны сүрөттө."},
    {"en": "Repeat", "pr": "рипит", "ky": "Кайтала", "ex": "Repeat please.", "ex_pr": "Рипит плиз.", "ex_ky": "Сураныч кайтала."},
    {"en": "Continue", "pr": "континью", "ky": "Улант", "ex": "Continue working.", "ex_pr": "Континью уоркинг.", "ex_ky": "Иштөөнү улант."},
    {"en": "Stop", "pr": "стоп", "ky": "Токто", "ex": "Stop the car.", "ex_pr": "Стоп зэ кар.", "ex_ky": "Машинаны токтот."},
    {"en": "Pause", "pr": "поз", "ky": "Пауза", "ex": "Pause the video.", "ex_pr": "Поз зэ видео.", "ex_ky": "Видеону паузага кой."},
    {"en": "Save", "pr": "сейв", "ky": "Сакта", "ex": "Save the file.", "ex_pr": "Сейв зэ файл.", "ex_ky": "Файлды сакта."},
    {"en": "Delete", "pr": "дилит", "ky": "Өчүр", "ex": "Delete this.", "ex_pr": "Дилит зис.", "ex_ky": "Муну өчүр."},
    {"en": "Copy", "pr": "копи", "ky": "Көчүр", "ex": "Copy the text.", "ex_pr": "Копи зэ текст.", "ex_ky": "Текстти көчүр."},
    {"en": "Paste", "pr": "пэйст", "ky": "Кой", "ex": "Paste here.", "ex_pr": "Пэйст хиэр.", "ex_ky": "Бул жакка кой."},
    {"en": "Print", "pr": "принт", "ky": "Басып чыгар", "ex": "Print the document.", "ex_pr": "Принт зэ документ.", "ex_ky": "Документти басып чыгар."},
    {"en": "Scan", "pr": "скан", "ky": "Скан", "ex": "Scan the QR code.", "ex_pr": "Скан зэ кьюар коуд.", "ex_ky": "QR кодту скан кыл."},
    {"en": "Upload", "pr": "аплоуд", "ky": "Жүктө", "ex": "Upload the file.", "ex_pr": "Аплоуд зэ файл.", "ex_ky": "Файлды жүктө."},
    {"en": "Download", "pr": "даунлоуд", "ky": "Жүктөп ал", "ex": "Download the app.", "ex_pr": "Даунлоуд зэ эп.", "ex_ky": "Приложениени жүктөп ал."},
    {"en": "Install", "pr": "инстол", "ky": "Орнот", "ex": "Install the software.", "ex_pr": "Инстол зэ софтуэр.", "ex_ky": "Программаны орнот."},
    {"en": "Update", "pr": "апдейт", "ky": "Жаңырт", "ex": "Update the system.", "ex_pr": "Апдейт зэ систим.", "ex_ky": "Системаны жаңырт."},
    {"en": "Restart", "pr": "ристарт", "ky": "Кайра күйгүз", "ex": "Restart the computer.", "ex_pr": "Ристарт зэ компьютир.", "ex_ky": "Компьютерди кайра күйгүз."},
    {"en": "Turn on", "pr": "тёрн он", "ky": "Күйгүз", "ex": "Turn on the light.", "ex_pr": "Тёрн он зэ лайт.", "ex_ky": "Жарыкты күйгүз."},
    {"en": "Turn off", "pr": "тёрн оф", "ky": "Өчүр", "ex": "Turn off the TV.", "ex_pr": "Тёрн оф зэ тиви.", "ex_ky": "Телевизорду өчүр."},
    {"en": "Charge", "pr": "чарж", "ky": "Кубатта", "ex": "Charge the phone.", "ex_pr": "Чарж зэ фоун.", "ex_ky": "Телефонду кубатта."},
    {"en": "Connect", "pr": "конект", "ky": "Туташ", "ex": "Connect to Wi-Fi.", "ex_pr": "Конект ту вай-фай.", "ex_ky": "Wi-Fi туташ."},
    {"en": "Disconnect", "pr": "дисконект", "ky": "Өчүр", "ex": "Disconnect the cable.", "ex_pr": "Дисконект зэ кейбл.", "ex_ky": "Кабелди өчүр."},
    {"en": "Login", "pr": "лог ин", "ky": "Кир", "ex": "Login to your account.", "ex_pr": "Лог ин ту ёр аккаунт.", "ex_ky": "Аккаунтыңа кир."},
    {"en": "Logout", "pr": "лог аут", "ky": "Чык", "ex": "Logout of the system.", "ex_pr": "Лог аут оф зэ систим.", "ex_ky": "Системадан чык."},
    {"en": "Sign in", "pr": "сайн ин", "ky": "Кир", "ex": "Sign in here.", "ex_pr": "Сайн ин хиэр.", "ex_ky": "Бул жакка кир."},
    {"en": "Sign up", "pr": "сайн ап", "ky": "Каттал", "ex": "Sign up now.", "ex_pr": "Сайн ап нау.", "ex_ky": "Азыр каттал."},
    {"en": "Search", "pr": "сёрч", "ky": "Изде", "ex": "Search on Google.", "ex_pr": "Сёрч он гу гул.", "ex_ky": "Google изде."},
    {"en": "Find", "pr": "файнд", "ky": "Тап", "ex": "Find the answer.", "ex_pr": "Файнд зэ ансэр.", "ex_ky": "Жоопту тап."},
    {"en": "Check", "pr": "чек", "ky": "Текшер", "ex": "Check your email.", "ex_pr": "Чек ёр имэйл.", "ex_ky": "Электрондук почтаңды текшер."},
    {"en": "Confirm", "pr": "конфирм", "ky": "Ыраста", "ex": "Confirm the order.", "ex_pr": "Конфирм зэ ордэр.", "ex_ky": "Буйрутманы ыраста."},
    {"en": "Cancel", "pr": "кэнсэл", "ky": "Жокко чыгар", "ex": "Cancel the booking.", "ex_pr": "Кэнсэл зэ букинг.", "ex_ky": "Бронированиени жокко чыгар."},
    {"en": "Accept", "pr": "аксепт", "ky": "Кабыл ал", "ex": "Accept the invitation.", "ex_pr": "Аксепт зэ инвитэйшн.", "ex_ky": "Чакырууну кабыл ал."},
    {"en": "Refuse", "pr": "рифьюз", "ky": "Баш тарт", "ex": "Refuse the offer.", "ex_pr": "Рифьюз зэ оффэр.", "ex_ky": "Сунуштан баш тарт."},
    {"en": "Allow", "pr": "алау", "ky": "Уруксат бер", "ex": "Allow me.", "ex_pr": "Алау ми.", "ex_ky": "Мага уруксат бер."},
    {"en": "Forbid", "pr": "форбид", "ky": "Тыюу сал", "ex": "I forbid you.", "ex_pr": "Ай форбид ю.", "ex_ky": "Мен сага тыюу салам."},
    {"en": "Remember", "pr": "римэмбэр", "ky": "Эсте", "ex": "Remember this day.", "ex_pr": "Римэмбэр зис дэй.", "ex_ky": "Бул күндү эсте."},
    {"en": "Forget", "pr": "форгет", "ky": "Унут", "ex": "Forget the past.", "ex_pr": "Форгет зэ паст.", "ex_ky": "Өткөндү унут."},
    {"en": "Imagine", "pr": "имэжин", "ky": "Элесте", "ex": "Imagine that.", "ex_pr": "Имэжин дэт.", "ex_ky": "Аны элесте."},
    {"en": "Suppose", "pr": "супоуз", "ky": "Болжолдо", "ex": "Suppose you are right.", "ex_pr": "Супоуз ю а райт.", "ex_ky": "Сен туура деп болжолдойлу."},
    {"en": "Guess", "pr": "гес", "ky": "Тап", "ex": "Guess the answer.", "ex_pr": "Гес зэ ансэр.", "ex_ky": "Жоопту тап."},
    {"en": "Decide", "pr": "дисайд", "ky": "Чечки", "ex": "Decide now.", "ex_pr": "Дисайд нау.", "ex_ky": "Азыр чечки."},
    {"en": "Choose", "pr": "чуз", "ky": "Танда", "ex": "Choose wisely.", "ex_pr": "Чуз вайзли.", "ex_ky": "Акылдуулук менен тандагыла."},
    {"en": "Select", "pr": "силэкт", "ky": "Танда", "ex": "Select the option.", "ex_pr": "Силэкт зэ опшн.", "ex_ky": "Вариантты танда."},
    {"en": "Pick", "pr": "пик", "ky": "Танда", "ex": "Pick a card.", "ex_pr": "Пик э кард.", "ex_ky": "Картаны танда."},
    {"en": "Mix", "pr": "микс", "ky": "Аралаштыр", "ex": "Mix the colors.", "ex_pr": "Микс зэ калерс.", "ex_ky": "Түстөрдү аралаштыр."},
    {"en": "Separate", "pr": "сэпэрэйт", "ky": "Бөл", "ex": "Separate them.", "ex_pr": "Сэпэрэйт дэм.", "ex_ky": "Аларды бөл."},
    {"en": "Add", "pr": "эд", "ky": "Кош", "ex": "Add sugar.", "ex_pr": "Эд шугар.", "ex_ky": "Кант кош."},
    {"en": "Subtract", "pr": "сабтракт", "ky": "Кемит", "ex": "Subtract five.", "ex_pr": "Сабтракт файв.", "ex_ky": "Бешти кемит."},
    {"en": "Multiply", "pr": "малтиплай", "ky": "Көбөйт", "ex": "Multiply by two.", "ex_pr": "Малтиплай бай ту.", "ex_ky": "Экиге көбөйт."},
    {"en": "Divide", "pr": "дивайд", "ky": "Бөл", "ex": "Divide by three.", "ex_pr": "Дивайд бай сри.", "ex_ky": "Үчкө бөл."},
    {"en": "Measure", "pr": "мэжэр", "ky": "Өлчө", "ex": "Measure the length.", "ex_pr": "Мэжэр зэ ленс.", "ex_ky": "Узундугун өлчө."},
    {"en": "Weigh", "pr": "уэй", "ky": "Тарт", "ex": "Weigh the fruit.", "ex_pr": "Уэй зэ фрут.", "ex_ky": "Жемишти тарт."},
    {"en": "Count", "pr": "каунт", "ky": "Сана", "ex": "Count to ten.", "ex_pr": "Каунт ту тэн.", "ex_ky": "Онго чейин сана."},
    {"en": "Calculate", "pr": "кэлкьюлейт", "ky": "Эсепте", "ex": "Calculate the total.", "ex_pr": "Кэлкьюлейт зэ тоутл.", "ex_ky": "Жалпы сумманы эсепте."},
    {"en": "Solve", "pr": "солв", "ky": "Чеч", "ex": "Solve the problem.", "ex_pr": "Солв зэ проблэм.", "ex_ky": "Көйгөйдү чеч."},
    {"en": "Prepare", "pr": "припэар", "ky": "Дайында", "ex": "Prepare the food.", "ex_pr": "Припэар зэ фуд.", "ex_ky": "Тамак даярда."},
    {"en": "Arrange", "pr": "арэйндж", "ky": "Тартипке сал", "ex": "Arrange the chairs.", "ex_pr": "Арэйндж зэ чэарс.", "ex_ky": "Орундуктарды тартипке сал."},
    {"en": "Organize", "pr": "органайз", "ky": "Уюштур", "ex": "Organize your room.", "ex_pr": "Органайз ёр рум.", "ex_ky": "Бөлмөңдү тазала."},
    {"en": "Plan", "pr": "план", "ky": "Планда", "ex": "Plan your day.", "ex_pr": "План ёр дэй.", "ex_ky": "Күнүңдү планда."},
    {"en": "Schedule", "pr": "шэдьюл", "ky": "График", "ex": "Schedule the meeting.", "ex_pr": "Шэдьюл зэ митинг.", "ex_ky": "Жыйынды графикке кой."},
    {"en": "Delay", "pr": "дилэй", "ky": "Кечеңд", "ex": "Don't delay.", "ex_pr": "Донт дилэй.", "ex_ky": "Кечеңдетпе."},
    {"en": "Hurry", "pr": "хари", "ky": "Шаш", "ex": "Hurry up.", "ex_pr": "Хари ап.", "ex_ky": "Шашкын."},
    {"en": "Wait", "pr": "уэйт", "ky": "Күт", "ex": "Wait a moment.", "ex_pr": "Уэйт э моумэнт.", "ex_ky": "Бир мүнөт күт."},
    {"en": "Arrive", "pr": "эрайв", "ky": "Кел", "ex": "Arrive on time.", "ex_pr": "Эрайв он тайм.", "ex_ky": "Убагында кел."},
    {"en": "Leave", "pr": "лив", "ky": "Кет", "ex": "Leave early.", "ex_pr": "Лив эрли.", "ex_ky": "Эрте кет."},
    {"en": "Return", "pr": "ритёрн", "ky": "Кайт", "ex": "Return home.", "ex_pr": "Ритёрн хоум.", "ex_ky": "Үйгө кайт."},
    {"en": "Enter", "pr": "энтэр", "ky": "Кир", "ex": "Enter the room.", "ex_pr": "Энтэр зэ рум.", "ex_ky": "Бөлмөгө кир."},
    {"en": "Exit", "pr": "эгзит", "ky": "Чык", "ex": "Exit the building.", "ex_pr": "Эгзит зэ билдинг.", "ex_ky": "Имараттан чык."},
    {"en": "Cross", "pr": "крос", "ky": "Кесип өт", "ex": "Cross the street.", "ex_pr": "Крос зэ стрит.", "ex_ky": "Көчөдөн өт."},
    {"en": "Turn", "pr": "тёрн", "ky": "Бурул", "ex": "Turn left.", "ex_pr": "Тёрн лэфт.", "ex_ky": "Солго бурул."},
    {"en": "Follow", "pr": "фолоу", "ky": "Ээрчи", "ex": "Follow me.", "ex_pr": "Фолоу ми.", "ex_ky": "Мени ээрчи."},
    {"en": "Lead", "pr": "лид", "ky": "Жетекте", "ex": "Lead the way.", "ex_pr": "Лид зэ уэй.", "ex_ky": "Жолду көрсөт."},
    {"en": "Guide", "pr": "гайд", "ky": "Жетекте", "ex": "Guide the tourist.", "ex_pr": "Гайд зэ турист.", "ex_ky": "Туристти жетекте."},
    {"en": "Direct", "pr": "дирэкт", "ky": "Багытта", "ex": "Direct the traffic.", "ex_pr": "Дирэкт зэ трэффик.", "ex_ky": "Транспортту багытта."},
    {"en": "Control", "pr": "контрол", "ky": "Башкар", "ex": "Control the car.", "ex_pr": "Контрол зэ кар.", "ex_ky": "Машинаны башкар."},
    {"en": "Manage", "pr": "мэнидж", "ky": "Башкар", "ex": "Manage the team.", "ex_pr": "Мэнидж зэ тим.", "ex_ky": "Команданы башкар."},
    {"en": "Supervise", "pr": "супэрвиз", "ky": "Көзөмөлдө", "ex": "Supervise the children.", "ex_pr": "Супэрвиз зэ чилдрэн.", "ex_ky": "Балдарды көзөмөлдө."},
    {"en": "Inspect", "pr": "инспект", "ky": "Текшер", "ex": "Inspect the goods.", "ex_pr": "Инспект зэ гудс.", "ex_ky": "Товарды текшер."},
    {"en": "Test", "pr": "тэст", "ky": "Сына", "ex": "Test the system.", "ex_pr": "Тэст зэ систим.", "ex_ky": "Системаны сына."},
    {"en": "Prove", "pr": "прув", "ky": "Далилде", "ex": "Prove it.", "ex_pr": "Прув ит.", "ex_ky": "Аны далилде."},
    {"en": "Show", "pr": "шоу", "ky": "Көрсөт", "ex": "Show me.", "ex_pr": "Шоу ми.", "ex_ky": "Мага көрсөт."},
    {"en": "Demonstrate", "pr": "дэмонстрэйт", "ky": "Көрсөтүү", "ex": "Demonstrate the product.", "ex_pr": "Дэмонстрэйт зэ продакт.", "ex_ky": "Продукцияны көрсөтүү."},
    {"en": "Explain", "pr": "иксплейн", "ky": "Түшүндүр", "ex": "Explain how it works.", "ex_pr": "Иксплейн хау ит уоркс.", "ex_ky": "Кантип иштээрин түшүндүр."},
    {"en": "Teach", "pr": "тич", "ky": "Үйрөт", "ex": "Teach me.", "ex_pr": "Тич ми.", "ex_ky": "Мага үйрөт."},
    {"en": "Learn", "pr": "лёрн", "ky": "Үйрөн", "ex": "Learn from me.", "ex_pr": "Лёрн фром ми.", "ex_ky": "Менден үйрөн."},
    {"en": "Study", "pr": "стади", "ky": "Оку", "ex": "Study hard.", "ex_pr": "Стади хард.", "ex_ky": "Катуу оку."},
    {"en": "Practice", "pr": "практис", "ky": "Машык", "ex": "Practice daily.", "ex_pr": "Практис дэйли.", "ex_ky": "Күн сайын машык."},
    {"en": "Repeat", "pr": "рипит", "ky": "Кайтала", "ex": "Repeat after me.", "ex_pr": "Рипит афтэр ми.", "ex_ky": "Менен кийин кайтала."},
    {"en": "Review", "pr": "ривью", "ky": "Кайталоо", "ex": "Review the lesson.", "ex_pr": "Ривью зэ лесн.", "ex_ky": "Сабакты кайталоо."},
    {"en": "Remember", "pr": "римэмбэр", "ky": "Эсте", "ex": "Remember the rules.", "ex_pr": "Римэмбэр зэ рулс.", "ex_ky": "Эрежелерди эсте."},
    {"en": "Understand", "pr": "андерстэнд", "ky": "Түшүн", "ex": "Understand me.", "ex_pr": "Андерстэнд ми.", "ex_ky": "Мени түшүн."},
    {"en": "Know", "pr": "ноу", "ky": "Бил", "ex": "Know the truth.", "ex_pr": "Ноу зэ трус.", "ex_ky": "Чындыкты бил."},
    {"en": "Realize", "pr": "риэлайз", "ky": "Түшүн", "ex": "Realize the mistake.", "ex_pr": "Риэлайз зэ мистэйк.", "ex_ky": "Катаны түшүн."},
    {"en": "Notice", "pr": "ноутис", "ky": "Байка", "ex": "Notice the change.", "ex_pr": "Ноутис зэ чейнж.", "ex_ky": "Өзгөрүүнү байка."},
    {"en": "Observe", "pr": "обзёрв", "ky": "Байка", "ex": "Observe carefully.", "ex_pr": "Обзёрв кэафули.", "ex_ky": "Кылдат байка."},
    {"en": "Watch", "pr": "уотч", "ky": "Көр", "ex": "Watch the movie.", "ex_pr": "Уотч зэ муви.", "ex_ky": "Тасманы көр."},
    {"en": "Look", "pr": "лук", "ky": "Кара", "ex": "Look at the board.", "ex_pr": "Лук эт зэ борд.", "ex_ky": "Тактага кара."},
    {"en": "See", "pr": "си", "ky": "Көр", "ex": "See you later.", "ex_pr": "Си ю лэйтэр.", "ex_ky": "Кийин көрүшөбүз."},
    {"en": "Glance", "pr": "глэнс", "ky": "Көз чаптыр", "ex": "Glance at the clock.", "ex_pr": "Глэнс эт зэ клок.", "ex_ky": "Саатка көз чаптыр."},
    {"en": "Stare", "pr": "стэар", "ky": "Тик", "ex": "Don't stare.", "ex_pr": "Донт стэар.", "ex_ky": "Тикпе."},
    {"en": "Blink", "pr": "блинк", "ky": "Көз ирме", "ex": "Blink your eyes.", "ex_pr": "Блинк ёр айз.", "ex_ky": "Көзүңдү ирме."},
    {"en": "Wink", "pr": "уинк", "ky": "Көз кыс", "ex": "Wink at me.", "ex_pr": "Уинк эт ми.", "ex_ky": "Мага көз кыс."},
    {"en": "Cry", "pr": "край", "ky": "Ыйла", "ex": "Don't cry.", "ex_pr": "Донт край.", "ex_ky": "Ыйлаба."},
    {"en": "Weep", "pr": "уип", "ky": "Ыйла", "ex": "Weep quietly.", "ex_pr": "Уип куайетли.", "ex_ky": "Тынч ыйла."},
    {"en": "Sob", "pr": "соб", "ky": "Ыкты", "ex": "Sob loudly.", "ex_pr": "Соб лаудли.", "ex_ky": "Катуу ыкта."},
    {"en": "Laugh", "pr": "лаф", "ky": "Күл", "ex": "Laugh out loud.", "ex_pr": "Лаф аут лауд.", "ex_ky": "Катуу күл."},
    {"en": "Giggle", "pr": "гигл", "ky": "Күлүмсүрө", "ex": "Giggle quietly.", "ex_pr": "Гигл куайетли.", "ex_ky": "Тынч күлүмсүрө."},
    {"en": "Smile", "pr": "смайл", "ky": "Жылмай", "ex": "Smile please.", "ex_pr": "Смайл плиз.", "ex_ky": "Сураныч жылмай."},
    {"en": "Frown", "pr": "фраун", "ky": "Кабагынан түйүл", "ex": "Don't frown.", "ex_pr": "Донт фраун.", "ex_ky": "Кабагыңды түйбө."},
    {"en": "Whisper", "pr": "уиспэр", "ky": "Шыбыра", "ex": "Whisper to me.", "ex_pr": "Уиспэр ту ми.", "ex_ky": "Мага шыбыра."},
    {"en": "Shout", "pr": "шаут", "ky": "Кыйкыр", "ex": "Don't shout.", "ex_pr": "Донт шаут.", "ex_ky": "Кыйкырба."},
    {"en": "Scream", "pr": "скрим", "ky": "Айкыр", "ex": "Scream for help.", "ex_pr": "Скрим фор хэлп.", "ex_ky": "Жардамга айкыр."},
    {"en": "Talk", "pr": "ток", "ky": "Сүйлөш", "ex": "Talk to me.", "ex_pr": "Ток ту ми.", "ex_ky": "Мени менен сүйлөш."},
    {"en": "Chat", "pr": "чат", "ky": "Чат", "ex": "Chat with me.", "ex_pr": "Чат уиз ми.", "ex_ky": "Мени менен чатташ."},
    {"en": "Discuss", "pr": "дискас", "ky": "Талкуула", "ex": "Discuss the problem.", "ex_pr": "Дискас зэ проблэм.", "ex_ky": "Көйгөйдү талкуула."},
    {"en": "Debate", "pr": "дибейт", "ky": "Талаш", "ex": "Debate the topic.", "ex_pr": "Дибейт зэ топик.", "ex_ky": "Теманы талаш."},
    {"en": "Convince", "pr": "конвинс", "ky": "Ынандыр", "ex": "Convince them.", "ex_pr": "Конвинс дэм.", "ex_ky": "Аларды ынандыр."},
    {"en": "Persuade", "pr": "пэруэйд", "ky": "Көндүр", "ex": "Persuade him.", "ex_pr": "Пэруэйд хим.", "ex_ky": "Аны көндүр."},
    {"en": "Encourage", "pr": "энкарэдж", "ky": "Үндө", "ex": "Encourage me.", "ex_pr": "Энкарэдж ми.", "ex_ky": "Мага үндө."},
    {"en": "Support", "pr": "сапорт", "ky": "Колдо", "ex": "Support me.", "ex_pr": "Сапорт ми.", "ex_ky": "Мени колдо."},
    {"en": "Help", "pr": "хэлп", "ky": "Жардам", "ex": "Help me please.", "ex_pr": "Хэлп ми плиз.", "ex_ky": "Мага жардам бер."},
    {"en": "Assist", "pr": "ассист", "ky": "Жардам", "ex": "Assist the customer.", "ex_pr": "Ассист зэ кастомер.", "ex_ky": "Кардарга жардам бер."},
    {"en": "Serve", "pr": "сёрв", "ky": "Кызмат кыл", "ex": "Serve the food.", "ex_pr": "Сёрв зэ фуд.", "ex_ky": "Тамакты кызмат кыл."},
    {"en": "Provide", "pr": "провайд", "ky": "Бери", "ex": "Provide the information.", "ex_pr": "Провайд зэ инфомэйшн.", "ex_ky": "Маалымат бер."},
    {"en": "Supply", "pr": "саплай", "ky": "Камсыз кыл", "ex": "Supply the goods.", "ex_pr": "Саплай зэ гудс.", "ex_ky": "Товарларды камсыз кыл."},
    {"en": "Give", "pr": "гив", "ky": "Бер", "ex": "Give me a chance.", "ex_pr": "Гив ми э чэнс.", "ex_ky": "Мага мүмкүнчүлүк бер."},
    {"en": "Offer", "pr": "оффэр", "ky": "Сунуш", "ex": "Offer your help.", "ex_pr": "Оффэр ёр хэлп.", "ex_ky": "Жардамыңды сунуш."},
    {"en": "Receive", "pr": "рисив", "ky": "Ал", "ex": "Receive the gift.", "ex_pr": "Рисив зэ гифт.", "ex_ky": "Белекти ал."},
    {"en": "Accept", "pr": "аксепт", "ky": "Кабыл ал", "ex": "Accept the offer.", "ex_pr": "Аксепт зэ оффэр.", "ex_ky": "Сунушту кабыл ал."},
    {"en": "Refuse", "pr": "рифьюз", "ky": "Баш тарт", "ex": "Refuse politely.", "ex_pr": "Рифьюз полайтли.", "ex_ky": "Сылык баш тарт."},
    {"en": "Reject", "pr": "риджэкт", "ky": "Четке каг", "ex": "Reject the idea.", "ex_pr": "Риджэкт зэ айдиэ.", "ex_ky": "Идеяны четке каг."},
    {"en": "Choose", "pr": "чуз", "ky": "Танда", "ex": "Choose carefully.", "ex_pr": "Чуз кэафули.", "ex_ky": "Кылдат танда."},
    {"en": "Select", "pr": "силэкт", "ky": "Танда", "ex": "Select the best.", "ex_pr": "Силэкт зэ бэст.", "ex_ky": "Эң жакшысын танда."},
    {"en": "Pick", "pr": "пик", "ky": "Танда", "ex": "Pick the right one.", "ex_pr": "Пик зэ райт уан.", "ex_ky": "Туурасын танда."},
    {"en": "Decide", "pr": "дисайд", "ky": "Чечки", "ex": "Decide quickly.", "ex_pr": "Дисайд куикли.", "ex_ky": "Тез чечки."},
    {"en": "Determine", "pr": "детёрмин", "ky": "Аныкта", "ex": "Determine the cause.", "ex_pr": "Детёрмин зэ коз.", "ex_ky": "Себебин аныкта."},
    {"en": "Resolve", "pr": "ризолв", "ky": "Чеч", "ex": "Resolve the issue.", "ex_pr": "Ризолв зэ ишью.", "ex_ky": "Маселени чеч."},
    {"en": "Solve", "pr": "солв", "ky": "Чеч", "ex": "Solve the puzzle.", "ex_pr": "Солв зэ пазл.", "ex_ky": "Табышмакты чеч."},
    {"en": "Answer", "pr": "ансэр", "ky": "Жооп бер", "ex": "Answer the question.", "ex_pr": "Ансэр зэ куэсчн.", "ex_ky": "Суроого жооп бер."},
    {"en": "Reply", "pr": "риплай", "ky": "Жооп бер", "ex": "Reply to me.", "ex_pr": "Риплай ту ми.", "ex_ky": "Мага жооп бер."},
    {"en": "Respond", "pr": "риспонд", "ky": "Жооп бер", "ex": "Respond quickly.", "ex_pr": "Риспонд куикли.", "ex_ky": "Тез жооп бер."},
    {"en": "React", "pr": "риэкт", "ky": "Реакция", "ex": "React calmly.", "ex_pr": "Риэкт камли.", "ex_ky": "Тынч реакция кыл."},
    {"en": "Act", "pr": "экт", "ky": "Аракет кыл", "ex": "Act now.", "ex_pr": "Экт нау.", "ex_ky": "Азыр аракет кыл."},
    {"en": "Behave", "pr": "бихейв", "ky": "Өзүн алып жүр", "ex": "Behave well.", "ex_pr": "Бихейв вэл.", "ex_ky": "Жакшы алып жүр."},
    {"en": "Move", "pr": "мув", "ky": "Кыймылда", "ex": "Move quickly.", "ex_pr": "Мув куикли.", "ex_ky": "Тез кыймылда."},
    {"en": "Shift", "pr": "шифт", "ky": "Жылдыр", "ex": "Shift the box.", "ex_pr": "Шифт зэ бокс.", "ex_ky": "Кутуну жылдыр."},
    {"en": "Transfer", "pr": "трансфёр", "ky": "Өткөр", "ex": "Transfer the money.", "ex_pr": "Трансфёр зэ мани.", "ex_ky": "Акчаны өткөр."},
    {"en": "Send", "pr": "сэнд", "ky": "Жөнөт", "ex": "Send the letter.", "ex_pr": "Сэнд зэ леттэр.", "ex_ky": "Катты жөнөт."},
    {"en": "Receive", "pr": "рисив", "ky": "Ал", "ex": "Receive the package.", "ex_pr": "Рисив зэ пэкидж.", "ex_ky": "Багетти ал."},
    {"en": "Get", "pr": "гет", "ky": "Ал", "ex": "Get the book.", "ex_pr": "Гет зэ бук.", "ex_ky": "Китепти ал."},
    {"en": "Bring", "pr": "бринг", "ky": "Алып кел", "ex": "Bring the chair.", "ex_pr": "Бринг зэ чэар.", "ex_ky": "Орундукти алып кел."},
    {"en": "Take", "pr": "тэйк", "ky": "Ал", "ex": "Take this.", "ex_pr": "Тэйк зис.", "ex_ky": "Муну ал."},
    {"en": "Fetch", "pr": "фетч", "ky": "Алып кел", "ex": "Fetch the ball.", "ex_pr": "Фетч зэ бол.", "ex_ky": "Допту алып кел."},
    {"en": "Carry", "pr": "кэри", "ky": "Ташы", "ex": "Carry the bag.", "ex_pr": "Кэри зэ бэг.", "ex_ky": "Багжды ташы."},
    {"en": "Hold", "pr": "холд", "ky": "Карма", "ex": "Hold my hand.", "ex_pr": "Холд май хэнд.", "ex_ky": "Менин колумду карма."},
    {"en": "Grab", "pr": "граб", "ky": "Карма", "ex": "Grab it.", "ex_pr": "Граб ит.", "ex_ky": "Аны карма."},
    {"en": "Catch", "pr": "кэтч", "ky": "Карма", "ex": "Catch the ball.", "ex_pr": "Кэтч зэ бол.", "ex_ky": "Допту карма."},
    {"en": "Throw", "pr": "сроу", "ky": "Ыргыт", "ex": "Throw the ball.", "ex_pr": "Сроу зэ бол.", "ex_ky": "Допту ыргыт."},
    {"en": "Drop", "pr": "дроп", "ky": "Түшүр", "ex": "Don't drop it.", "ex_pr": "Донт дроп ит.", "ex_ky": "Аны түшүрбө."},
    {"en": "Push", "pr": "пуш", "ky": "Түрт", "ex": "Push the door.", "ex_pr": "Пуш зэ дор.", "ex_ky": "Эшикти түрт."},
    {"en": "Pull", "pr": "пул", "ky": "Тарт", "ex": "Pull the rope.", "ex_pr": "Пул зэ роуп.", "ex_ky": "Арканды тарт."},
    {"en": "Lift", "pr": "лифт", "ky": "Көтөр", "ex": "Lift the weight.", "ex_pr": "Лифт зэ уэйт.", "ex_ky": "Салмакты көтөр."},
    {"en": "Abandon", "pr": "эбэндон", "ky": "Таштап кет", "ex": "Don't abandon me.", "ex_pr": "Донт эбэндон ми.", "ex_ky": "Мени таштап кетпе."},
    {"en": "Ability", "pr": "эбилити", "ky": "Жөндөм", "ex": "I have the ability.", "ex_pr": "Ай хэв зэ эбилити.", "ex_ky": "Менде жөндөм бар."},
    {"en": "Able", "pr": "эйбл", "ky": "Жөндөмдүү", "ex": "I am able to do it.", "ex_pr": "Ай эм эйбл ту ду ит.", "ex_ky": "Мен муну кыла алам."},
    {"en": "Above", "pr": "эбав", "ky": "Үстүндө", "ex": "Above the sky.", "ex_pr": "Эбав зэ скай.", "ex_ky": "Асмандын үстүндө."},
    {"en": "Abroad", "pr": "эброд", "ky": "Чет өлкө", "ex": "I want to go abroad.", "ex_pr": "Ай уонт ту гоу эброд.", "ex_ky": "Мен чет өлкөгө кетким келет."},
    {"en": "Absent", "pr": "эбсент", "ky": "Жок", "ex": "He is absent today.", "ex_pr": "Хи из эбсент тудэй.", "ex_ky": "Ал бүгүн жок."},
    {"en": "Absolute", "pr": "эбсолут", "ky": "Абсолюттук", "ex": "Absolute truth.", "ex_pr": "Эбсолут трус.", "ex_ky": "Абсолюттук чындык."},
    {"en": "Accept", "pr": "аксепт", "ky": "Кабыл алуу", "ex": "Accept the truth.", "ex_pr": "Аксепт зэ трус.", "ex_ky": "Чындыкты кабыл ал."},
    {"en": "Access", "pr": "эксес", "ky": "Жетүү", "ex": "Access denied.", "ex_pr": "Эксес динайд.", "ex_ky": "Кирүүгө тыюу салынган."},
    {"en": "Accident", "pr": "эксидэнт", "ky": "Кырсык", "ex": "Car accident.", "ex_pr": "Кар эксидэнт.", "ex_ky": "Машина кырсыгы."},
    {"en": "Account", "pr": "экаунт", "ky": "Эсеп", "ex": "Bank account.", "ex_pr": "Бэнк экаунт.", "ex_ky": "Банк эсеби."},
    {"en": "Achieve", "pr": "эчив", "ky": "Жетүү", "ex": "Achieve your goal.", "ex_pr": "Эчив ёр гоул.", "ex_ky": "Макасатыңа жет."},
    {"en": "Acknowledge", "pr": "экнолиж", "ky": "Моюнга алуу", "ex": "Acknowledge the mistake.", "ex_pr": "Экнолиж зэ мистэйк.", "ex_ky": "Катаны моюнга ал."},
    {"en": "Across", "pr": "экрос", "ky": "Аркылуу", "ex": "Across the street.", "ex_pr": "Экрос зэ стрит.", "ex_ky": "Көчөнүн аркы өйүзүндө."},
    {"en": "Action", "pr": "экшн", "ky": "Аракет", "ex": "Take action.", "ex_pr": "Тэйк экшн.", "ex_ky": "Аракет кыл."},
    {"en": "Active", "pr": "эктив", "ky": "Активдүү", "ex": "Stay active.", "ex_pr": "Стэй эктив.", "ex_ky": "Активдүү бол."},
    {"en": "Actual", "pr": "экчуал", "ky": "Чыныгы", "ex": "Actual price.", "ex_pr": "Экчуал прайс.", "ex_ky": "Чыныгы баа."},
    {"en": "Addicted", "pr": "эдиктэд", "ky": "Көз каранды", "ex": "Addicted to phone.", "ex_pr": "Эдиктэд ту фоун.", "ex_ky": "Телефонго көз каранды."},
    {"en": "Address", "pr": "эдрес", "ky": "Дарек", "ex": "What is your address?", "ex_pr": "Уот из ёр эдрес?", "ex_ky": "Сиздин дарегиңиз кандай?"},
    {"en": "Admit", "pr": "эдмит", "ky": "Моюнга алуу", "ex": "Admit your fault.", "ex_pr": "Эдмит ёр фолт.", "ex_ky": "Күнөөңдү моюнга ал."},
    {"en": "Adopt", "pr": "эдопт", "ky": "Кабыл алуу", "ex": "Adopt a child.", "ex_pr": "Эдопт э чайлд.", "ex_ky": "Бала асырап алуу."},
    {"en": "Adult", "pr": "эдалт", "ky": "Чоң киши", "ex": "Adult life.", "ex_pr": "Эдалт лайф.", "ex_ky": "Чоң кишинин жашоосу."},
    {"en": "Advance", "pr": "эдванс", "ky": "Алдыга жыл", "ex": "Advance in career.", "ex_pr": "Эдванс ин кэриэр.", "ex_ky": "Карьерада алдыга жыл."},
    {"en": "Advice", "pr": "эдвайс", "ky": "Кеңеш", "ex": "Give me advice.", "ex_pr": "Гив ми эдвайс.", "ex_ky": "Мага кеңеш бер."},
    {"en": "Affect", "pr": "эфект", "ky": "Таасир этүү", "ex": "It affects me.", "ex_pr": "Ит эфектс ми.", "ex_ky": "Бул мага таасир этет."},
    {"en": "Afford", "pr": "эфорд", "ky": "Көтөрүү", "ex": "I can afford it.", "ex_pr": "Ай кэн эфорд ит.", "ex_ky": "Мен аны көтөрө алам."},
    {"en": "Afraid", "pr": "эфрэйд", "ky": "Коркуу", "ex": "I am afraid.", "ex_pr": "Ай эм эфрэйд.", "ex_ky": "Мен корком."},
    {"en": "Again", "pr": "эгейн", "ky": "Кайра", "ex": "Do it again.", "ex_pr": "Ду ит эгейн.", "ex_ky": "Кайра кыл."},
    {"en": "Against", "pr": "эгейнст", "ky": "Каршы", "ex": "Against the rules.", "ex_pr": "Эгейнст зэ рулс.", "ex_ky": "Эрежеге каршы."},
    {"en": "Age", "pr": "эйж", "ky": "Жаш", "ex": "What is your age?", "ex_pr": "Уот из ёр эйж?", "ex_ky": "Сиздин жашыңыз канча?"},
    {"en": "Agent", "pr": "эйжэнт", "ky": "Агент", "ex": "Travel agent.", "ex_pr": "Трэвэл эйжэнт.", "ex_ky": "Туризм агенти."},
    {"en": "Agree", "pr": "эгри", "ky": "Макул болуу", "ex": "I agree.", "ex_pr": "Ай эгри.", "ex_ky": "Мен макулмун."},
    {"en": "Ahead", "pr": "эхэд", "ky": "Алдыда", "ex": "Go ahead.", "ex_pr": "Гоу эхэд.", "ex_ky": "Алдыга жүр."},
    {"en": "Aid", "pr": "эйд", "ky": "Жардам", "ex": "First aid.", "ex_pr": "Фёрст эйд.", "ex_ky": "Тез жардам."},
    {"en": "Aim", "pr": "эйм", "ky": "Маңдай", "ex": "Aim for success.", "ex_pr": "Эйм фор саксес.", "ex_ky": "Ийгиликке маңдай."},
    {"en": "Air", "pr": "эар", "ky": "Аба", "ex": "Fresh air.", "ex_pr": "Фрэш эар.", "ex_ky": "Таза аба."},
    {"en": "Alarm", "pr": "элам", "ky": "Которгуч", "ex": "Set an alarm.", "ex_pr": "Сэт эн элам.", "ex_ky": "Которгуч кой."},
    {"en": "Alcohol", "pr": "элкэхол", "ky": "Спирт", "ex": "No alcohol.", "ex_pr": "Ноу элкэхол.", "ex_ky": "Спирт ичпе."},
    {"en": "Alert", "pr": "элёрт", "ky": "Эскертүү", "ex": "Stay alert.", "ex_pr": "Стэй элёрт.", "ex_ky": "Абайлап жүр."},
    {"en": "Alien", "pr": "эйлиен", "ky": "Чет элдик", "ex": "Alien from space.", "ex_pr": "Эйлиен фром спэйс.", "ex_ky": "Космостон келген чет элдик."},
    {"en": "Alive", "pr": "элайв", "ky": "Тирүү", "ex": "I am alive.", "ex_pr": "Ай эм элайв.", "ex_ky": "Мен тирүүмүн."},
    {"en": "All", "pr": "ол", "ky": "Баары", "ex": "All of us.", "ex_pr": "Ол оф ас.", "ex_ky": "Баарыбыз."},
    {"en": "Allow", "pr": "элау", "ky": "Уруксат берүү", "ex": "Allow me.", "ex_pr": "Элау ми.", "ex_ky": "Мага уруксат бер."},
    {"en": "Almost", "pr": "олмоуст", "ky": "Дээрлик", "ex": "Almost done.", "ex_pr": "Олмоуст дан.", "ex_ky": "Дээрлик бүттү."},
    {"en": "Alone", "pr": "элоун", "ky": "Жалгыз", "ex": "I am alone.", "ex_pr": "Ай эм элоун.", "ex_ky": "Мен жалгызмын."},
    {"en": "Along", "pr": "элонг", "ky": "Бойлой", "ex": "Along the road.", "ex_pr": "Элонг зэ роуд.", "ex_ky": "Жолдун бойлой."},
    {"en": "Already", "pr": "олрэди", "ky": "Буга чейин", "ex": "I already know.", "ex_pr": "Ай олрэди ноу.", "ex_ky": "Мен буга чейин билем."},
    {"en": "Also", "pr": "олсоу", "ky": "Ошондой эле", "ex": "I also like it.", "ex_pr": "Ай олсоу лайк ит.", "ex_ky": "Мен аны ошондой эле жактырам."},
    {"en": "Although", "pr": "олзоу", "ky": "Бирок", "ex": "Although it's hard.", "ex_pr": "Олзоу итс хард.", "ex_ky": "Бирок ал кыйын."},
    {"en": "Always", "pr": "олуэйз", "ky": "Ар дайым", "ex": "Always be kind.", "ex_pr": "Олуэйз би кайнд.", "ex_ky": "Ар дайым боорукер бол."},
    {"en": "Amazing", "pr": "эмэйзинг", "ky": "Таң калычтуу", "ex": "You are amazing.", "ex_pr": "Ю ар эмэйзинг.", "ex_ky": "Сен таң калычтуусуң."},
    {"en": "Ambition", "pr": "эмбишн", "ky": "Тырыштык", "ex": "Great ambition.", "ex_pr": "Грэйт эмбишн.", "ex_ky": "Чоң тырыштык."},
    {"en": "Amount", "pr": "эмаунт", "ky": "Сан", "ex": "Large amount.", "ex_pr": "Лардж эмаунт.", "ex_ky": "Чоң сан."},
    {"en": "Analyze", "pr": "энелайз", "ky": "Анализдөө", "ex": "Analyze the data.", "ex_pr": "Энелайз зэ дэйта.", "ex_ky": "Берилиштерди анализде."},
    {"en": "Ancient", "pr": "эйншнт", "ky": "Байыркы", "ex": "Ancient history.", "ex_pr": "Эйншнт хистори.", "ex_ky": "Байыркы тарых."},
    {"en": "Anger", "pr": "энггэр", "ky": "Ачуу", "ex": "Control your anger.", "ex_pr": "Контрол ёр энггэр.", "ex_ky": "Ачууңду башкар."},
    {"en": "Angle", "pr": "энггл", "ky": "Бурч", "ex": "Right angle.", "ex_pr": "Райт энггл.", "ex_ky": "Туура бурч."},
    {"en": "Animal", "pr": "энимал", "ky": "Жаныбар", "ex": "Wild animal.", "ex_pr": "Уайлд энимал.", "ex_ky": "Жапайы жаныбар."},
    {"en": "Announce", "pr": "энаунс", "ky": "Жарыялоо", "ex": "Announce the news.", "ex_pr": "Энаунс зэ ньюз.", "ex_ky": "Жаңылыкты жарыяла."},
    {"en": "Annoy", "pr": "эной", "ky": "Ачууландыруу", "ex": "You annoy me.", "ex_pr": "Ю эной ми.", "ex_ky": "Сен мени ачууландырасың."},
    {"en": "Answer", "pr": "ансэр", "ky": "Жооп", "ex": "Wrong answer.", "ex_pr": "Ронг ансэр.", "ex_ky": "Ката жооп."},
    {"en": "Antique", "pr": "энтик", "ky": "Антиквариат", "ex": "Antique shop.", "ex_pr": "Энтик шоп.", "ex_ky": "Антиквариат дүкөнү."},
    {"en": "Anxious", "pr": "энгкшос", "ky": "Тынчсыз", "ex": "I feel anxious.", "ex_pr": "Ай фил энгкшос.", "ex_ky": "Мен өзүмдү тынчсыз сезем."},
    {"en": "Anyway", "pr": "эниуэй", "ky": "Кантсе да", "ex": "Anyway, let's go.", "ex_pr": "Эниуэй, летс гоу.", "ex_ky": "Кантсе да, кеттик."},
    {"en": "Apart", "pr": "эпарт", "ky": "Бөлүк", "ex": "Fall apart.", "ex_pr": "Фол эпарт.", "ex_ky": "Бөлүнүп кетүү."},
    {"en": "Apartment", "pr": "эпартмэнт", "ky": "Квартира", "ex": "Small apartment.", "ex_pr": "Смол эпартмэнт.", "ex_ky": "Кичине квартира."},
    {"en": "Apologize", "pr": "эполоджайз", "ky": "Кечирим суроо", "ex": "I apologize.", "ex_pr": "Ай эполоджайз.", "ex_ky": "Мен кечирим сурайм."},
    {"en": "Appeal", "pr": "эпил", "ky": "Өтүнүү", "ex": "Appeal to everyone.", "ex_pr": "Эпил ту эвриуан.", "ex_ky": "Баарына өтүнүү."},
    {"en": "Appear", "pr": "эпиэр", "ky": "Пайда болуу", "ex": "Appear out of nowhere.", "ex_pr": "Эпиэр аут оф ноууэа.", "ex_ky": "Күтүлбөгөн жерден пайда болду."},
    {"en": "Apple", "pr": "эпл", "ky": "Алма", "ex": "Red apple.", "ex_pr": "Рэд эпл.", "ex_ky": "Кызыл алма."},
    {"en": "Apply", "pr": "эплай", "ky": "Колдонуу", "ex": "Apply for a job.", "ex_pr": "Эплай фор э джоб.", "ex_ky": "Жумушка көмүскөнүү."},
    {"en": "Appoint", "pr": "эпоинт", "ky": "Дайындоо", "ex": "Appoint a manager.", "ex_pr": "Эпоинт э мэниджэр.", "ex_ky": "Менеджерди дайындоо."},
    {"en": "Appreciate", "pr": "эпришиэт", "ky": "Баалоо", "ex": "I appreciate you.", "ex_pr": "Ай эпришиэт ю.", "ex_ky": "Мен сени баалайм."},
    {"en": "Approach", "pr": "эпроуч", "ky": "Жакындоо", "ex": "Approach carefully.", "ex_pr": "Эпроуч кэафули.", "ex_ky": "Абайлап жакында."},
    {"en": "Approve", "pr": "эпрув", "ky": "Колдоо", "ex": "I approve.", "ex_pr": "Ай эпрув.", "ex_ky": "Мен колдойм."},
    {"en": "Area", "pr": "эриэ", "ky": "Аймак", "ex": "Restricted area.", "ex_pr": "Ристриктэд эриэ.", "ex_ky": "Чектелген аймак."},
    {"en": "Argue", "pr": "аргью", "ky": "Талашуу", "ex": "Don't argue.", "ex_pr": "Донт аргью.", "ex_ky": "Талашпа."},
    {"en": "Arise", "pr": "эрайз", "ky": "Көтөрүлүү", "ex": "Problems arise.", "ex_pr": "Проблэмз эрайз.", "ex_ky": "Көйгөйлөр көтөрүлөт."},
    {"en": "Arm", "pr": "арм", "ky": "Кол", "ex": "Break your arm.", "ex_pr": "Брэйк ёр арм.", "ex_ky": "Колуңду сындыр."},
    {"en": "Army", "pr": "арми", "ky": "Аскер", "ex": "Join the army.", "ex_pr": "Джойн зэ арми.", "ex_ky": "Аскерге барып кошул."},
    {"en": "Around", "pr": "эраунд", "ky": "Айланасында", "ex": "Around the world.", "ex_pr": "Эраунд зэ уорлд.", "ex_ky": "Дүйнөнүн айланасында."},
    {"en": "Arrange", "pr": "эрэйнж", "ky": "Уюштуруу", "ex": "Arrange a meeting.", "ex_pr": "Эрэйнж э митинг.", "ex_ky": "Жыйын уюштуруу."},
    {"en": "Arrest", "pr": "эрэст", "ky": "Камоого алуу", "ex": "Arrest the thief.", "ex_pr": "Эрэст зэ сиф.", "ex_ky": "Ууруну камоого ал."},
    {"en": "Arrive", "pr": "эрайв", "ky": "Келүү", "ex": "Arrive on time.", "ex_pr": "Эрайв он тайм.", "ex_ky": "Убагында кел."},
    {"en": "Arrow", "pr": "эроу", "ky": "Жаа", "ex": "Bow and arrow.", "ex_pr": "Боу энд эроу.", "ex_ky": "Жаа менен жебе."},
    {"en": "Art", "pr": "арт", "ky": "Искусство", "ex": "Modern art.", "ex_pr": "Модэн арт.", "ex_ky": "Заманбап искусство."},
    {"en": "Article", "pr": "артикл", "ky": "Макала", "ex": "Read the article.", "ex_pr": "Рид зэ артикл.", "ex_ky": "Макаланы оку."},
    {"en": "Artificial", "pr": "артифишл", "ky": "Жасалма", "ex": "Artificial intelligence.", "ex_pr": "Артифишл интеллиженс.", "ex_ky": "Жасалма интеллект."},
    {"en": "Artist", "pr": "артист", "ky": "Сүрөтчү", "ex": "Famous artist.", "ex_pr": "Фэймос артист.", "ex_ky": "Атактуу сүрөтчү."},
    {"en": "Ash", "pr": "эш", "ky": "Күл", "ex": "Burn to ash.", "ex_pr": "Бёрн ту эш.", "ex_ky": "Күл болуп күй."},
    {"en": "Aside", "pr": "эсайд", "ky": "Четке", "ex": "Step aside.", "ex_pr": "Стэп эсайд.", "ex_ky": "Четке бас."},
    {"en": "Ask", "pr": "аск", "ky": "Суроо", "ex": "Ask a question.", "ex_pr": "Аск э куэсчн.", "ex_ky": "Суроо бер."},
    {"en": "Asleep", "pr": "эслип", "ky": "Уктап", "ex": "Fall asleep.", "ex_pr": "Фол эслип.", "ex_ky": "Уктап кал."},
    {"en": "Assault", "pr": "эсолт", "ky": "Кол салуу", "ex": "Physical assault.", "ex_pr": "Физикл эсолт.", "ex_ky": "Денеге кол салуу."},
    {"en": "Assume", "pr": "эсюм", "ky": "Болжолдоо", "ex": "I assume so.", "ex_pr": "Ай эсюм соу.", "ex_ky": "Мен ошондой болжолдойм."},
    {"en": "Assure", "pr": "эшур", "ky": "Кепилдөө", "ex": "I assure you.", "ex_pr": "Ай эшур ю.", "ex_ky": "Мен сага кепил берем."},
    {"en": "Astonish", "pr": "эстониш", "ky": "Таң калуу", "ex": "You astonish me.", "ex_pr": "Ю эстониш ми.", "ex_ky": "Сен мени таң калтырасың."},
    {"en": "Attack", "pr": "этэк", "ky": "Кол салуу", "ex": "Attack the enemy.", "ex_pr": "Этэк зэ энеми.", "ex_ky": "Душманга кол сал."},
    {"en": "Attempt", "pr": "этэмпт", "ky": "Аракет кылуу", "ex": "Attempt again.", "ex_pr": "Этэмпт эгейн.", "ex_ky": "Кайра аракет кыл."},
    {"en": "Attend", "pr": "этэнд", "ky": "Катышуу", "ex": "Attend the meeting.", "ex_pr": "Этэнд зэ митинг.", "ex_ky": "Жыйынга катыш."},
    {"en": "Attention", "pr": "этеншн", "ky": "Көңүл", "ex": "Pay attention.", "ex_pr": "Пэй этэншн.", "ex_ky": "Көңүл бур."},
    {"en": "Attitude", "pr": "этитюд", "ky": "Мамиле", "ex": "Positive attitude.", "ex_pr": "Позитив этитюд.", "ex_ky": "Оң мамиле."},
    {"en": "Attract", "pr": "этрэкт", "ky": "Өзүнө тартуу", "ex": "Attract attention.", "ex_pr": "Этрэкт этэншн.", "ex_ky": "Көңүлдү өзүнө тарт."},
    {"en": "Audience", "pr": "одиенс", "ky": "Укпай", "ex": "Live audience.", "ex_pr": "Лив одиенс.", "ex_ky": "Түз укпай."},
    {"en": "August", "pr": "огэст", "ky": "Август", "ex": "August is hot.", "ex_pr": "Огэст из хот.", "ex_ky": "Август ысык."},
    {"en": "Aunt", "pr": "ант", "ky": "Таеже", "ex": "My aunt is nice.", "ex_pr": "Май ант из найс.", "ex_ky": "Менин таежем жакшы."},
    {"en": "Author", "pr": "офор", "ky": "Автор", "ex": "Famous author.", "ex_pr": "Фэймос офор.", "ex_ky": "Атактуу автор."},
    {"en": "Authority", "pr": "офорити", "ky": "Бийлик", "ex": "Local authority.", "ex_pr": "Лоукл офорити.", "ex_ky": "Жергиликтүү бийлик."},
    {"en": "Automatic", "pr": "отомэтик", "ky": "Автоматтык", "ex": "Automatic door.", "ex_pr": "Отомэтик дор.", "ex_ky": "Автоматтык эшик."},
    {"en": "Autumn", "pr": "отум", "ky": "Күз", "ex": "Beautiful autumn.", "ex_pr": "Бьютифл отум.", "ex_ky": "Кооз күз."},
    {"en": "Avalanche", "pr": "эвэлэнч", "ky": "Кар көчкүсү", "ex": "Dangerous avalanche.", "ex_pr": "Дэйнджэрос эвэлэнч.", "ex_ky": "Коркунучтуу кар көчкүсү."},
    {"en": "Average", "pr": "эвэридж", "ky": "Орточо", "ex": "Average height.", "ex_pr": "Эвэридж хайт.", "ex_ky": "Орточо бийиктик."},
    {"en": "Avoid", "pr": "эвойд", "ky": "Качуу", "ex": "Avoid danger.", "ex_pr": "Эвойд дэйнджэр.", "ex_ky": "Коркунучтан кач."},
    {"en": "Awake", "pr": "эуэйк", "ky": "Ойгонуу", "ex": "Stay awake.", "ex_pr": "Стэй эуэйк.", "ex_ky": "Ойгонуп тур."},
    {"en": "Award", "pr": "эуорд", "ky": "Сыйлык", "ex": "Win an award.", "ex_pr": "Уин эн эуорд.", "ex_ky": "Сыйлык жең."},
    {"en": "Aware", "pr": "эуэар", "ky": "Кабардар", "ex": "Be aware.", "ex_pr": "Би эуэар.", "ex_ky": "Кабардар бол."},
    {"en": "Awful", "pr": "офул", "ky": "Бетон", "ex": "Awful weather.", "ex_pr": "Офул уэзэр.", "ex_ky": "Бетон аба ырайы."},
    {"en": "Awkward", "pr": "окворд", "ky": "Ыңгайсыз", "ex": "Awkward situation.", "ex_pr": "Окворд сичуэйшн.", "ex_ky": "Ыңгайсыз кырдаал."},
    {"en": "Baby", "pr": "бэйби", "ky": "Нарсте", "ex": "Cute baby.", "ex_pr": "Кьют бэйби.", "ex_ky": "Сүйкүмдүү нарсте."},
    {"en": "Back", "pr": "бэк", "ky": "Арткы", "ex": "Back door.", "ex_pr": "Бэк дор.", "ex_ky": "Арткы эшик."},
    {"en": "Background", "pr": "бэкграунд", "ky": "Фон", "ex": "White background.", "ex_pr": "Уайт бэкграунд.", "ex_ky": "Ак фон."},
    {"en": "Backward", "pr": "бэкворд", "ky": "Артка", "ex": "Step backward.", "ex_pr": "Стэп бэкворд.", "ex_ky": "Артка кадам ташта."},
    {"en": "Bacteria", "pr": "бэктириэ", "ky": "Бактерия", "ex": "Harmful bacteria.", "ex_pr": "Хамфул бэктириэ.", "ex_ky": "Зыяндуу бактерия."},
    {"en": "Badge", "pr": "бэдж", "ky": "Белги", "ex": "Police badge.", "ex_pr": "Поли бэдж.", "ex_ky": "Полиция белгиси."},
    {"en": "Bag", "pr": "бэг", "ky": "Багж", "ex": "Paper bag.", "ex_pr": "Пэйпэр бэг.", "ex_ky": "Багж кагаз."},
    {"en": "Bake", "pr": "бэйк", "ky": "Бышыруу", "ex": "Bake a cake.", "ex_pr": "Бэйк э кэйк.", "ex_ky": "Торт бышыр."},
    {"en": "Balance", "pr": "бэлэнс", "ky": "Тең салмак", "ex": "Keep balance.", "ex_pr": "Кип бэлэнс.", "ex_ky": "Тең салмакты сакта."},
    {"en": "Ball", "pr": "бол", "ky": "Топ", "ex": "Kick the ball.", "ex_pr": "Кик зэ бол.", "ex_ky": "Топту теп."},
    {"en": "Bamboo", "pr": "бэмбу", "ky": "Башпалык", "ex": "Bamboo forest.", "ex_pr": "Бэмбу форист.", "ex_ky": "Башпалык токою."},
    {"en": "Band", "pr": "бэнд", "ky": "Топ", "ex": "Music band.", "ex_pr": "Мьюзик бэнд.", "ex_ky": "Музыкалык топ."},
    {"en": "Bank", "pr": "бэнк", "ky": "Банк", "ex": "Central bank.", "ex_pr": "Сэнтрэл бэнк.", "ex_ky": "Борбордук банк."},
    {"en": "Bar", "pr": "бар", "ky": "Бар", "ex": "Coffee bar.", "ex_pr": "Кофи бар.", "ex_ky": "Кофе бар."},
    {"en": "Bare", "pr": "бэар", "ky": "Жылаңач", "ex": "Bare feet.", "ex_pr": "Бэар фит.", "ex_ky": "Жылаңач бут."},
    {"en": "Bark", "pr": "барк", "ky": "Үрүү", "ex": "Dogs bark.", "ex_pr": "Догс барк.", "ex_ky": "Иттер үрөт."},
    {"en": "Barn", "pr": "барн", "ky": "Сарай", "ex": "Old barn.", "ex_pr": "Олд барн.", "ex_ky": "Эски сарай."},
    {"en": "Barrier", "pr": "бэриэ", "ky": "Тоскоолдук", "ex": "Language barrier.", "ex_pr": "Лэнгвидж бэриэ.", "ex_ky": "Тил тоскоолдугу."},
    {"en": "Base", "pr": "бэйс", "ky": "Негиз", "ex": "Base of the building.", "ex_pr": "Бэйс оф зэ билдинг.", "ex_ky": "Имараттын негизи."},
    {"en": "Basic", "pr": "бэйсик", "ky": "Негизги", "ex": "Basic rules.", "ex_pr": "Бэйсик рулс.", "ex_ky": "Негизги эрежелер."},
    {"en": "Basket", "pr": "баскит", "ky": "Себет", "ex": "Fruit basket.", "ex_pr": "Фрут баскит.", "ex_ky": "Жемиш себети."},
    {"en": "Bat", "pr": "бэт", "ky": "Жарганат", "ex": "Flying bat.", "ex_pr": "Флайинг бэт.", "ex_ky": "Учуучу жарганат."},
    {"en": "Bath", "pr": "бас", "ky": "Ванна", "ex": "Take a bath.", "ex_pr": "Тэйк э бас.", "ex_ky": "Ванна кабыл ал."},
    {"en": "Battle", "pr": "бэтл", "ky": "Салгылашуу", "ex": "Epic battle.", "ex_pr": "Эпик бэтл.", "ex_ky": "Эпикалык салгылашуу."},
    {"en": "Beach", "pr": "бич", "ky": "Пляж", "ex": "Sandy beach.", "ex_pr": "Сэнди бич.", "ex_ky": "Кумдуу пляж."},
    {"en": "Bead", "pr": "бид", "ky": "Мончок", "ex": "Glass bead.", "ex_pr": "Глас бид.", "ex_ky": "Айнек мончок."},
    {"en": "Beak", "pr": "бик", "ky": "Тумшук", "ex": "Bird's beak.", "ex_pr": "Бёрдс бик.", "ex_ky": "Куштун тумшугу."},
    {"en": "Bean", "pr": "бин", "ky": "Буурчак", "ex": "Coffee bean.", "ex_pr": "Кофи бин.", "ex_ky": "Кофе буурчагы."},
    {"en": "Bear", "pr": "бэар", "ky": "Аюу", "ex": "Brown bear.", "ex_pr": "Браун бэар.", "ex_ky": "Күрөң аюу."},
    {"en": "Beard", "pr": "бирд", "ky": "Сак", "ex": "Long beard.", "ex_pr": "Лонг бирд.", "ex_ky": "Узун сак."},
    {"en": "Beast", "pr": "бист", "ky": "Айбан", "ex": "Mythical beast.", "ex_pr": "Мисикл бист.", "ex_ky": "Уламыштагы айбан."},
    {"en": "Beat", "pr": "бит", "ky": "Кагуу", "ex": "Beat the drum.", "ex_pr": "Бит зэ дралм.", "ex_ky": "Добул кага."},
    {"en": "Bed", "pr": "бэд", "ky": "Төшөк", "ex": "Make the bed.", "ex_pr": "Мэйк зэ бэд.", "ex_ky": "Төшөктү жай."},
    {"en": "Bedroom", "pr": "бэдрум", "ky": "Уктоо бөлмөсү", "ex": "Clean bedroom.", "ex_pr": "Клин бэдрум.", "ex_ky": "Таза уктоо бөлмөсү."},
    {"en": "Bee", "pr": "би", "ky": "Аары", "ex": "Busy bee.", "ex_pr": "Бизи би.", "ex_ky": "Кыймылдуу аары."},
    {"en": "Beef", "pr": "биф", "ky": "Уй эти", "ex": "Roast beef.", "ex_pr": "Рост биф.", "ex_ky": "Уй эти кебабы."}
];
